### ISSUE TITLE
GET /v2/users/:guid/summary is very slow when the user is in many orgs

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/cloud_controller_ng#2182] opened 2021-04-06 06:59 UTC
## Issue

If a user is in 100 orgs, the GET /v2/users/:guid/summary is very slow and high CPU consumption. 

## Context

The user summary is generated from https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/presenters/api/user_summary_presenter.rb. 

Assuming a user is in 1000 orgs with manager, billing manager and audit manager roles, each org has 1 space and with the same quota definition, I think it will trigger many queries to multiple tables, as below:

query number | table name
   4                    | organizations
  4000                |  quota_definitions
  4003                | spaces
  4001                 |  users

I think so many queries slows down this API call, and the map operation in these Presenters consumes a lot of CPU.

## Steps to Reproduce

1. Have user is in 1000 orgs with manager, billing manager and audit manager roles, each org has 1 space and with the same quota definition
2. run "cf curl /v2/users/:guid/summary"

## Expected result

Expect the GET /v2/users/:guid/summary is fast and consume less CPU.

## Current result

Some users are in about 1000 orgs, when the API `GET /v2/users/:guid/summary` was called many times in parallel, the CPU usage of CC got increased from 20% to 90%, and the CC thread pool was exhausted, then CC could not handle any other requests.

## Possible Fix

If the organization object queried from database can be cached in memory, I think maybe that could reduce the queries significantly.

For the above example, the query number possible will be low:

query number | table name
   4                    | organizations     
  1000                |  quota_definitions  
  1003                | spaces  
  1001                 |  users

Any other ideas to improvet he performance? thanks.

**Comment by sweinstein22** [comment] 2021-04-07 20:43
Hi @JimmyMa ,

At this point v2 has been deprecated so we're not making changes to the v2 endpoints. In the new structure of users and roles the user summary endpoint information can be accessed via the [`v3/roles?user_guids=:guid` endpoint](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html#list-roles), where `organization` and `space` can be passed to the `include` query parameter.

This new endpoint is paginated, while the v2 user summary endpoint was not, which should help mitigate the load from a single call. I have also run the `v3/roles` query with the max page size (5000 resources per page) and the `/v2/users/:guid/summary` query against an environment populated as detailed above, and it takes about half as long to retrieve the data when leveraging the `v3` endpoint.

Would moving to the v3 endpoints be sufficient for your use case?

**Comment by JimmyMa** [comment] 2021-04-08 07:26
@sweinstein22 thank you, we will evaluate the new api `v3/roles` .

**Comment by JimmyMa** [comment] 2021-04-08 08:10
@sweinstein22 

Our CAPI version is 1.106 , and when I run `cf curl "/v3/roles?user_guids=345229f6-3479-4ba9-9fd5-f38cc2462069&per_page=1"` , it returned 504 as below, the user is only in one org.

````
cf curl "/v3/roles?user_guids=345229f6-3479-4ba9-9fd5-f38cc2462069&per_page=1"
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The sql query in postgres is below, and it took 289259.887 ms.

```
2021-04-08 07:46:54.591 GMTLOG:  duration: 289259.887 ms  statement: SELECT count(*) AS "count" FROM (SELECT * FROM (SELECT 'organization_user' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_users" UNION ALL (SELECT 'organization_manager' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_managers") UNION ALL (SELECT 'organization_billing_manager' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_billing_managers") UNION ALL (SELECT 'organization_auditor' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_auditors") UNION ALL (SELECT 'space_developer' AS "type", "role_guid" AS "guid", "user_id", -1 AS "organization_id", "space_id", "created_at", "updated_at" FROM "spaces_developers") UNION ALL (SELECT 'space_auditor' AS "type", "role_guid" AS "guid", "user_id", -1 AS "organization_id", "space_id", "created_at", "updated_at" FROM "spaces_auditors") UNION ALL (SELECT 'space_manager' AS "type", "role_guid" AS "guid", "user_id", -1 AS "organization_id", "space_id", "created_at", "updated_at" FROM "spaces_managers")) AS "t1" WHERE ("space_id" IN (SELECT "id" FROM "spaces")) UNION (SELECT * FROM (SELECT 'organization_user' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_users" UNION ALL (SELECT 'organization_manager' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_managers") UNION ALL (SELECT 'organization_billing_manager' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_billing_managers") UNION ALL (SELECT 'organization_auditor' AS "type", "role_guid" AS "guid", "user_id", "organization_id", -1 AS "space_id", "created_at", "updated_at" FROM "organizations_auditors") UNION ALL (SELECT 'space_developer' AS "type", "role_guid" AS "guid", "user_id", -1 AS "organization_id", "space_id", "created_at", "updated_at" FROM "spaces_developers") UNION ALL (SELECT 'space_auditor' AS "type", "role_guid" AS "guid", "user_id", -1 AS "organization_id", "space_id", "created_at", "updated_at" FROM "spaces_auditors") UNION ALL (SELECT 'space_manager' AS "type", "role_guid" AS "guid", "user_id", -1 AS "organization_id", "space_id", "created_at", "updated_at" FROM "spaces_managers")) AS "t1" WHERE ("organization_id" IN (SELECT "id" FROM "organizations")))) AS "t1" WHERE ("user_id" IN (SELECT "id" FROM "users" WHERE ("guid" IN ('345229f6-3479-4ba9-9fd5-f38cc2462069')))) LIMIT 1
```

Should we verify it with the latest CAPI version? thanks.

**Comment by sweinstein22** [comment] 2021-04-08 19:12
Hi @JimmyMa ,

I just ran it against the development environment I've been testing against and found that `cf curl "/v3/roles?user_guids=:guid&per_page=1"` returned without issue in a fraction of a second. I don't believe any changes have been made to the roles endpoint since `1.106.0` was released, but I am working on the latest version, `1.109.0`, so it could be worth checking against the latest version.

**Comment by sethboyles** [comment] 2021-04-12 22:20
@JimmyMa  can you provide a few more details about the structure of your database?  How many users do you have?  And approximately how many roles per user?

I am also not able to reproduce this with a single user in 1000 orgs with 3 roles per org.  However, I tested this on MySql.  Perhaps it is an issue with Postgres...

**Comment by sethboyles** [comment] 2022-02-04 18:48
Closing due to lack of response

**Closed by sethboyles** 2022-02-04 18:48 UTC
Labels: unscheduled, performance
