### ISSUE TITLE
Slow api calls for routes and apps endpoints 

### ISSUE THREAD

**Issue by claudio-benfatto** [cloudfoundry/cloud_controller_ng#678] opened 2016-09-09 11:12 UTC
## Issue

In production we experience very slow api calls when hitting certain endpoints
## Context

We are running an on-premise CF installation, and using the following versions:
- CF version is `237`
- Diego version is `0.1472.0`
- The version of the cf cli command is: `cf version 6.21.0+dff2cf8-2016-07-27`
- We have enabled the newrelic Cloud Controller integration
## Steps to Reproduce

hitting the `routes` and `apps` endpoints via cli ie. `cf routes` and `cf apps` or just curling them, executes very slowly for target organizations with many apps deployed and many routes and produces a huge resultset (around _76MB_ for an organization with ~300 apps deployed and ~500 routes) 

ie:

```
claudio@claudio-ThinkPad-T450s:~$ time cf routes
Getting routes for org <redacted> / space live as admin ...

....

real    2m49.855s
user    0m2.868s
sys    0m0.232s
```
## Expected result

Those api calls should perform much better
## Current result

We noticed the following query is executed examining NewRelic and Postgresql:

`
SELECT DISTINCT "apps".*, "apps_routes"."route_id" AS "x_foreign_key_x" FROM "apps" INNER JOIN "apps_routes" ON ("apps_routes"."app_id" = "apps"."id") WHERE ("apps_routes"."route_id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)) ORDER BY "id" ASC
`

with a running time of: 122,000 ms

Moreover while analysing the same query in postgresql we noticed that an ordering step is involved (as expected) :
`Sort (cost=5049.25..5055.61 rows=2545 width=1454)`

but that this ordering operation is using as **Sort Key** all the columns in the SELECT . This involves a quicksort on a very huge resultset against many text columns and seems to be utterly inefficient.

Running the same query with : 
`SELECT DISTINCT ON (apps.id) ...` solves the problem, as well as eliminating the `ORDER BY` clause in the end (because postgresql in this case uses a more efficient `GROUP BY` operations behind the curtains)
![slow_query](https://cloud.githubusercontent.com/assets/7601067/18384990/b4fd2bfc-7685-11e6-88d9-39ca7f1e2db0.png)

Let me know if you need more data. I can produce it on request.

Thank you for your help,
Claudio

**Comment by claudio-benfatto** [comment] 2016-09-13 15:26
Some more details about the query involved:

[analyse.txt](https://github.com/cloudfoundry/cloud_controller_ng/files/470196/analyse.txt)

**Comment by SocalNick** [comment] 2016-10-19 23:09
@claudio-benfatto we may be able to make that optimization, but we are curious why you have 300 apps and 500 routes in a single space? It seems as though this would be very unmanageable, regardless of the API response time. Can you partition your apps and routes into smaller spaces?

**Comment by jshiell** [comment] 2016-10-25 12:08
I'm one of the devs using that space, and in particular we have one application with ~500 routes. This is a nginx container that's responsible for transforming legacy requests to our journal delivery platform, and given we have about 490 legacy domains to support (no longer used, but they need to redirect existing bookmarks to the appropriate content on the new platform) we need to map an unusually large amount of routes to this application. Despite it being a bit irritating to look at in the CLI, I can assure you it's very manageable 😄 

Given it's primarily a single application, splitting across spaces won't be possible. Which leaves us with the options of either splitting the app into multiple deployments of multiple instances, where each deployment has a subset of the mappings, or in moving this application out of CF entirely. Given our stack is based around all requests being routed to CF, this is hardly trivial.

For the record - looking at the space at present, we appears to have about 58 active applications in that space, which seems very reasonable (especially since most of them are micro services related directly to this single platform), and another  64 stopped apps. It's possible that this number could have increased to the ~300 you mention if the stopped app cleanup scripts hadn't been run recently for some reason, but I would imagine the number I give above are a more usual reflection of the usage of this space.

**Comment by claudio-benfatto** [comment] 2016-10-25 13:21
@jshiell thanks for your help!

@SocalNick I confirm those numbers and the fact that we happened to have ~300 apps as a result of a malfunctioning of the clean-up script. 
We are also very keen to find a solution which would allow us to keep the routing logic within cloudfoundry itself after migrating to Diego.

Thanks!

**Comment by SocalNick** [comment] 2016-10-25 20:59
@jshiell can you describe the translation between the legacy domains and the new platform? Does it respond with HTTP redirect? Is it just a domain change or does it also change the request path?

cc @ematpl RE: Diego 4KB limit

**Comment by jshiell** [comment] 2016-10-25 22:07
@SocalNick it's either a reverse-proxy to the modern stack, or a HTTP redirect to the new stack location. It'll change both the domain and the path, and - in the case of articles - it involves a DB lookup to do this, so I fear it's not just something we can replace with domain level redirects.

**Comment by SocalNick** [comment] 2016-10-28 00:17
@jshiell we'll take a look at your query optimization suggestion.

@dkoper this might be a CLI UX concern as well, not sure if you can optimize `cf routes` and `cf apps` for the above

**Comment by aashah** [comment] 2016-11-10 22:39
Hey,

Thanks for opening this issue.

We deployed a copy of cf-release v237, but were unfortunately unable to reproduce this. We did see the query above, however we were caught off guard to see your select query was not paginated like ours was. The CC API prevents listing more than 100 entries per page.

```
$ cf curl "/v2/apps/:app_guid/routes?order-direction=asc&page=1&results-per-page=500"
{
   "code": 10005,
   "description": "The query parameter is invalid: results_per_page must be <= 100",
   "error_code": "CF-BadQueryParameter"
}
```

Furthermore, we deployed roughly 600 routes amongst 100 apps total, and our commands (`cf routes`, curls, and manual database queries) finished within reasonable timings. Our longest operation (`cf routes`) took 4 seconds. Our deployment was on bosh-lite, which may account for some of the timings being so different.

Most of all, we'd like to better understand where that query came from. We have been unable to reproduce the circumstances by which that query is made.

- CAPI Community pair @aashah & @simonleung8

**Comment by claudio-benfatto** [comment] 2016-11-14 10:39
Thank you @aashah for looking into the issue.

One of the main differences I can tell in respect to the testing scenario you've implemented is that we happened to have several (10-15), applications with ~600 routes *each* at the same time. This may have made a difference.
Plus ofc the external Postgres database.

Yes, I see how pagination could have affected the result. I'll try to have a better look at the query in order to track its origin.
Furthermore, after fixing our clean-up script we haven't  experienced anymore the same bad behaviour.

Thanks for now!
Claudio

**Comment by michaelxupiv** [comment] 2016-12-16 19:03
Hey @claudio-benfatto,

Thanks for your input. We'll close this issue for now, but feel free to reopen it if you experience problems again.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv

**Closed by michaelxupiv** 2016-12-16 19:03 UTC
Labels: unscheduled
