### ISSUE TITLE
Occasionally, `cf unbind-service` seems to fail and not unbind, even though the service broker operation was successful

### ISSUE THREAD

**Issue by silvestre** [cloudfoundry/cloud_controller_ng#1210] opened 2018-09-03 11:37 UTC
## Issue

Occasionally, `cf unbind-service` seems to fail even if the service broker responds with a successful deletion, which leads to service instance not being unbound from the app.

## Context

We have **occasionally** observed that users were not able to unbind service instances from an app.
When they issue a `cf unbind-service` the service broker gets called with a DELETE on the appropriate binding resource, the deletion is audit logged and then the end-user gets an error message and the binding is not removed from the app.

## Steps to Reproduce

1. cf unbind-service

## Expected result

Successful unbinding, service binding is removed in the broker

## Current result

Unbinding is not successful, even though service binding was removed in the broker

Here are some the logs that show the problem:
The service broker received and processed the unbind at August 26th 2018, 08:00:21.486:
```
user 'cloudcontroller' at client 'xxx' sent request 'DELETE /v2/service_instances/3c9e55c5-5343-48a1-b527-54248a340cfa/service_bindings/a4da5beb-f23c-4448-b757-189a62c4dc71' with response code 'OK' and message 'Unbound service instance binding with id a4da5beb-f23c-4448-b757-189a62c4dc71 from service instance with id 3c9e55c5-5343-48a1-b527-54248a340cfa'
```
On August 26th 2018, 08:00:21.510 the unbind was audit logged by the CC:

```
{"timestamp":1535263221.5107431,"message":"(0.002702s) INSERT INTO \"events\" (\"type\", \"actor\", \"actor_type\", \"actor_name\", \"actor_username\", \"actee\", \"actee_type\", \"actee_name\", \"space_guid\", \"organization_guid\", \"timestamp\", \"metadata\", \"created_at\", \"updated_at\", \"guid\") VALUES ('audit.service_binding.delete', '719710de-a44c-4184-8427-3a846a7cf0e8', 'user', 'xxx', 'xxx', 'a4da5beb-f23c-4448-b757-189a62c4dc71', 'service_binding', '', 'da504186-e5a8-4085-919d-513923e1e9ba', '23ef5087-8f89-4390-bdc2-7195b36233b9', CURRENT_TIMESTAMP, '{\"request\":{\"app_guid\":\"add7989a-8e41-4b9e-a36f-7b0164b3e1f9\",\"service_instance_guid\":\"3c9e55c5-5343-48a1-b527-54248a340cfa\"}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '868029a6-c298-4501-99eb-a5cee9c557f1') RETURNING *","log_level":"info","source":"cc.db","data":{"request_guid":"5090c0ce-2477-4c8d-70c7-f88aed24e1ef::5bb9f46a-d58f-45c9-b507-60d15d8f0572"},"thread_id":47261997817580,"fiber_id":70049708818820,"process_id":7005,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb","lineno":88,"method":"block in log_each"}
```
However, the unbind did not actually succeed and different end-users retry it, and the service broker responds with 410 Gone as it should according to OSB API, and the Cloud Controller logs it, too:

service broker August 26th 2018, 08:02:15.661:
```
 user 'cloudcontroller' at client 'xxx' sent request 'DELETE /v2/service_instances/3c9e55c5-5343-48a1-b527-54248a340cfa/service_bindings/a4da5beb-f23c-4448-b757-189a62c4dc71' with response code 'Gone' and message 'Service instance binding with id a4da5beb-f23c-4448-b757-189a62c4dc71 was already unbound from service instance with id 3c9e55c5-5343-48a1-b527-54248a340cfa'
```

CC August 26th 2018, 08:02:15.663:
```
{"timestamp":1535263335.6639955,"message":"Already deleted: https://service-broker/v2/service_instances/3c9e55c5-5343-48a1-b527-54248a340cfa/service_bindings/a4da5beb-f23c-4448-b757-189a62c4dc71","log_level":"warn","source":"cc.service_broker.v2.client","data":{"request_guid":"0d064ec4-5209-487b-7b73-baa67218328e::7aa73de0-9d9a-4209-b005-2f33466b127f"},"thread_id":47377758954620,"fiber_id":47377756389960,"process_id":7092,"file":"/var/vcap/data/packages/cloud_controller_ng/772c1711e503d7335ace40a27607d9959bcf3a59/cloud_controller_ng/lib/services/service_brokers/v2/response_parser.rb","lineno":82,"method":"parse_unbind"}

{"timestamp":1535263335.6701798,"message":"(0.001350s) INSERT INTO \"events\" (\"type\", \"actor\", \"actor_type\", \"actor_name\", \"actor_username\", \"actee\", \"actee_type\", \"actee_name\", \"space_guid\", \"organization_guid\", \"timestamp\", \"metadata\", \"created_at\", \"updated_at\", \"guid\") VALUES ('audit.service_binding.delete', '719710de-a44c-4184-8427-3a846a7cf0e8', 'user', 'yyy', 'yyy', 'a4da5beb-f23c-4448-b757-189a62c4dc71', 'service_binding', '', 'da504186-e5a8-4085-919d-513923e1e9ba', '23ef5087-8f89-4390-bdc2-7195b36233b9', CURRENT_TIMESTAMP, '{\"request\":{\"app_guid\":\"add7989a-8e41-4b9e-a36f-7b0164b3e1f9\",\"service_instance_guid\":\"3c9e55c5-5343-48a1-b527-54248a340cfa\"}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '2b8db03e-87a1-449a-905f-19ed2728ff0b') RETURNING *","log_level":"info","source":"cc.db","data":{"request_guid":"0d064ec4-5209-487b-7b73-baa67218328e::7aa73de0-9d9a-4209-b005-2f33466b127f"},"thread_id":47377758954620,"fiber_id":47377756389960,"process_id":7092,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb","lineno":88,"method":"block in log_each"}
```
This repeats two times.

To me it looks like cloud controller bug as it receives the correct service brokers responses, audit logs the success, and still does not remove the binding.

Is there anything that would help debug this? We don't keep logs for a long time, and the error occurred only two times (that we know of) in the last month, so it might take a while to gather more logs if you need them.

**Comment by mattmcneeney** [comment] 2018-09-10 10:13
Thanks for raising this @silvestre 
We've pulled this into our backlog to investigate and will let you know if we have any further questions.

**Comment by williammartin** [comment] 2018-10-15 15:45
Hi @silvestre, when you say "However, the unbind did not actually succeed", does the CLI (or curl request) succeed but not actually remove the binding, or does it fail with some error message?

**Comment by mattmcneeney** [comment] 2018-10-22 10:21
Friendly reminder for @silvestre to take a look at this if you can! We will leave this another week before closing.

**Comment by mattmcneeney** [comment] 2018-10-26 13:01
Closing this as we haven't had further feedback and can't reproduce this.

**Closed by mattmcneeney** 2018-10-26 13:01 UTC
Labels: sapi, scheduled
