### ISSUE TITLE
Database Deadlock on specific query

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/cloud_controller_ng#1363] opened 2019-06-05 14:46 UTC
## Issue

We get Database Deadlock occasionally by CC. These happen when people try to push an app. They then get a Database Error message in their CF-Push response. We have more detailed logs attached below.

## Context

CF 9.0.0 

## Steps to Reproduce

Not able to reproduce yet, we think it may be related to cc updates.
As updates where made shortly before the error occurred this could correlate.

## Expected result

No deadlocks and aborted transactions.

## Current result

Users occationally get a CF-Push error saying a DB Error occured
We observed this approximately 5 times. Users are then unable to push for a few seconds up to minutes.
Without further actions this issue goes away until it comes again.

```
{"timestamp":1559301591.9601736,"message":"PG::TRDeadlockDetected: ERROR: deadlock detected\nDETAIL: Process 424899 waits for ShareLock on transaction 5870269; blocked by process 427227.\nProcess 427227 waits for ShareLock on transaction 5870267; blocked by process 424899.\nHINT: See server log for query details.\nCONTEXT: while deleting tuple (11,3) in relation \"builds\": DELETE FROM \"builds\" WHERE \"id\" = 18871","log_level":"error","source":"cc.db", ..... }
```

It is always the same query, Delete from builds.

**Comment by sklevenz** [comment] 2019-12-06 07:57
We identified this query which is causing the deadlock.

`2019-12-05 17:13:39 UTC:10.0.65.68(54880):ccadmin@ccdb:[15972]:STATEMENT: ALTER TABLE "spaces_developers" ADD COLUMN "role_guid" varchar(255), ADD COLUMN "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, ADD COLUMN "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL`

The issue seems to be related to database migration while update and in parallel we had load on the system. By this situation we could reproduce the issue. After stopping all cc worker (== stopping the load) the migration went through.

**Comment by johha** [comment] 2019-12-06 08:44
To add some context: 
We noticed that the cc_worker nodes and api nodes were updated at the same time:
```LOG
Task 16184818 | 13:38:02 | Updating instance cc-worker: cc-worker/e597d744-7bd6-4228-9617-cd2b2627f2d4 (0) (canary)
Task 16184818 | 13:38:08 | Updating instance api: api/0bc6d14d-a274-4f78-ac13-e213e40a7078 (0) (canary)
Task 16184818 | 13:40:56 | Updating instance cc-worker: cc-worker/e597d744-7bd6-4228-9617-cd2b2627f2d4 (0) (canary) (00:02:54)
Task 16184818 | 13:40:56 | Updating instance cc-worker: cc-worker/5c2fb9b6-f692-47e2-a481-211234c53141 (4)
Task 16184818 | 13:42:00 | Updating instance api: api/0bc6d14d-a274-4f78-ac13-e213e40a7078 (0) (canary) (00:03:52)
                     L Error: Action Failed get_task: Task c968e90c-7f40-48d3-4d74-f8c015254bb8 result: 1 of 7 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: sysctl, bpm, bosh-dns, syslog_forwarder, cc_uploader, policy-server.
Task 16184818 | 13:43:50 | Updating instance cc-worker: cc-worker/5c2fb9b6-f692-47e2-a481-211234c53141 (4) (00:02:54)
```
As bosh starts the update with the cc_workers (13:38:02) they expect that the ccdb is migrated (Error in cc_worker nodes: `Sequel::Migrator::NotCurrentError: migrator is not current`). However the migration has not yet started because the update of the api node (incl. migration) starts a bit later (13:38:08). Furthermore we noticed that with the occurrence of the `migrator is not current` error the CPU usage of cc_workers goes up to 100%.

We'll check if the parallel update of cc_workers and api nodes is an issue on our side but I thought this is some helpful information.

**Comment by cwlbraa** [comment] 2019-12-10 00:39
@reid47 would you and VAT be interested in looking into this? It sounds related to v3 roles.

**Comment by FloThinksPi** [comment] 2019-12-17 02:35
Just to link things up, the matching story on the pivot tracker is https://www.pivotaltracker.com/story/show/170321550 
And also other tests showed similar behaviour: https://cloudfoundry.slack.com/archives/C07C04W4Q/p1576506597004900

**Comment by sethboyles** [comment] 2020-05-08 22:23
@FloThinksPi it looks like in February the V3 Acceleration team put out a fix for this.  Have you been able to check to see if their fix resolved the issue for you or not?

**Comment by sklevenz** [comment] 2020-05-11 12:50
@sethboyles Thanks for notification. We will discuss this fix and come back with feedback.

**Comment by Gerg** [comment] 2020-08-07 16:20
I'm going to close this issue for inactivity. Feel free to re-open if you are still seeing this issue.

Thanks!
Greg

**Closed by Gerg** 2020-08-07 16:20 UTC
Labels: bug, unscheduled
