### ISSUE TITLE
inconsistent hostname taken error messaging

### ISSUE THREAD

**Issue by adowns01** [cloudfoundry/cloud_controller_ng#731] opened 2016-11-28 23:32 UTC
## inconsistent hostname taken error messaging

There are no other apps in *my* spaces or orgs named `a`, but there *could* be in ones that I don't have access to.  When I run `cf push a` I get one error:

```
FAILED
Server error, status code: 400, error code: 210003, message: The host is taken: a
```

When there is an app `b` in space1 and I run `cf push b` in space2 I get another, nicer, error: 
```
{
  "code": 1002,
  "description": "Invalid relation: The requested route relation is invalid: 858eebc7-915a-4d14-9589-78426a9be20e",
  "error_code": "CF-InvalidRelation"
}

FAILED
The route b.cfapps.ctf-blue.cf-app.com is already in use.
TIP: Change the hostname with -n HOSTNAME or use --random-route to generate a new route and then push again.
```

## Context

I found this while on both the blue and red environments on hack day. 

## Steps to Reproduce

Not sure if other spaces/orgs that I don't have access to have an app with the hostname `a`. 

1. `cf push a` -> see the not nice error
2. `cf push b` in space1
3. `cf push b` in space2 -> see a nice error

## Expected result
I want it to always see the nice error.

**Comment by aashah** [comment] 2016-12-08 01:33
Hey @adowns01,

We were able to reproduce this, but as we looked closer this looks to be something on the side of the CLI. For the not-nice error, CC is actually returning a great error_code that the CLI isn't showing very nicely. See the below output:

nice-error logs:
```
$ curl to "PUT /v2/apps/<app guid>/routes/<route guid>"
{
  "code": 1002,
  "description": "Invalid relation: The requested route relation is invalid: c064fb44-502e-4c9d-a093-c45f339aaad0",
  "error_code": "CF-InvalidRelation"
}

FAILED
The route b.bosh-lite.com is already in use.
TIP: Change the hostname with -n HOSTNAME or use --random-route to generate a new route and then push again.
```

not-nice-error logs:
```
$ curl to "POST /v2/routes?async=true&inline-relations-depth=1"
{
  "code": 210003,
  "description": "The host is taken: a",
  "error_code": "CF-RouteHostTaken"
}

OK

FAILED
Server error, status code: 400, error code: 210003, message: The host is taken: a
```

In the second output, we're giving a very specific error (`CF-RouteHostTaken`).

Since this is more of a CLI issue, we're going to close this.
We'll see if there's a way to move this issue to the CLI repo though.

Thanks,
CAPI Community Pair - @aashah & @michaelxupiv

**Closed by aashah** 2016-12-08 01:33 UTC
Labels: unscheduled
