### ISSUE TITLE
API docs incorrect for v2 spaces

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/cloud_controller_ng#704] opened 2016-10-24 20:51 UTC
Hi,

http://apidocs.cloudfoundry.org/245/spaces/update_a_space.html says that one can do a PUT on the space to change the organization guid - this is not AFAIK correct.  It is probably worthwhile with the new flattened API docs to check that they are completely accurate.

**Comment by luan** [comment] 2016-12-06 23:34
Hi @ScarletTanager,

We addressed the documentation issue. The field is actually acceptable in that request, the issue is that the only valid value you can pass in is the guid of the currently associated org, and it will default to that.
This is not a particularly useful field to have in the API request, but it allows one to pass in the full space object back to the API, enabling for scripting and automation.

Thanks,
@luan & @ericpromislow, CF CAPI Team

**Comment by ScarletTanager** [comment] 2016-12-07 15:08
@luan - what you say about passing in the complete object makes sense from a scripting/automation perspective.  The commit looks good to me, do you want to close the issue or should I?

**Comment by SocalNick** [comment] 2016-12-09 00:39
I'd like to try to eliminate the 500 and instead return a 4xx with message like, `The organization_guid field cannot be changed`.

**Comment by SocalNick** [comment] 2016-12-12 22:31
Documentation change and returning 400 will be in next CAPI-Release

**Closed by SocalNick** 2016-12-12 22:31 UTC
Labels: accepted
