### ISSUE TITLE
Cloud Controller Keeps the status of Service Instance as "Update in Progress"

### ISSUE THREAD

**Issue by kamath-prasad** [cloudfoundry/cloud_controller_ng#817] opened 2017-05-05 14:13 UTC
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Cloud Controller does not call the broker API for polling last operation after the first call to PATCH instance is made. 

## Context

- On cf update-service <service-instance> , cloud controller makes a HTTP Patch call our service broker and our service broker has responded with HTTP 202 based on the API specifications provided here : https://docs.cloudfoundry.org/services/api.html .
- For many service instances , the cloud controller has thereafter made a call to Poll for the last Operation and hence updated the status for the service instance as either "Update Succeeded" or "Update Failed" .
- However there are a lot of service instances for which the cloud controller has not made even a single call to Poll for the last Operation ( dont know the reason why - no errors in the logs ) and hence the status of all those service instances in cloud controller is  still "Update in Progress". The broker however has completed the actions based on the first PATCH call and would have responded with success if the last_operation call was made by the cloud controller.
-  This has left lot of service instances to be un-usable since the cloud controller has the status of those as still "Update in Progress"

Is there a way to simulate the Cloud Controller to call the last_operation on the service-broker so that the status in cloud-controller can be updated ? If not , is are there any steps to be followed to update the status of the service instances in cloud controller database ?  We know that a 'cf purge-service-instance` works on these service instances , but we do not want to lose the service instances as we have some critical information stored in them. 

Let us know if you need more details .

**Comment by nicregez** [comment] 2017-05-12 18:36
Hey @kamath-prasad,

Thank you for reaching out to us.

We have started analyzing the issue you've raised, and we'd like to get some more information about your environment usage of services.

1. Have you found that a consistent steps reproduce this issue?
1. Could we see an example response body for the HTTP Patch call to the service broker? Specifically we are looking for any keys in addition to `operation`.

Regards,
CAPI Community Pair @aashah @nicregez

**Comment by kamath-prasad** [comment] 2017-05-17 13:56
@nicregez :

Have you found that a consistent steps reproduce this issue?

Ans : Unfortunately no . There were no logs in Cloud Controller that suggests any error when the PATCH instance call was made also.

Could we see an example response body for the HTTP Patch call to the service broker? Specifically we are looking for any keys in addition to operation.

Ans : Since we work on the service-broker , we can tell you the sequence things that resulted in this issue : 

- A PUT call was made to the Cloud Controller from the service-broker to update these service instances . (https://apidocs.cloudfoundry.org/258/service_instances/update_a_service_instance.html) .

Following are the details of that call from the serivce broker  : 

HTTP Method : PUT
URL : /v2/service_instances/:instance_id?accepts_incomplete=true
Request Body : { parameters : { 'service-fabrik-operation' : 'URL Encoded string'} }

- Cloud Controller made a corresponding PATCH instance call to the service-broker and below are the details of the response from the service-broker back to the cloud controller in the response body: 

 res.body = 
{
 operation: 'BASE64 ENCODED STRING'
} 

The BASE64 Encoded String is a JSON object : 

{
                  taskId : 1234,
		  type: 'update',
		  'service-fabrik-operation' : 'URL Encoded string'
}

Please let us know if you need any other details.

**Comment by nicregez** [comment] 2017-05-17 14:03
You write

> A PUT call was made to the Cloud Controller from the service-broker

Are you meaning that the service broker calls the Cloud Controller? Are you having a circular dependency between the two? Or is there a misunderstanding from my side?

**Comment by kamath-prasad** [comment] 2017-05-17 14:07
Yes , in this particular instance the first call was made by service-broker to the cloud controller to update the service instance as this process is triggered outside the cf cli for our use case. And we do this so that cloud controller locks the service instance from update by all other means.

**Comment by nicregez** [comment] 2017-05-17 14:17
I have never seen such a setup before, I have to admit I do not understand its purpose and that according to the service broker REST API specification, the dependency between the platform (Cloud Foundry - client) and the broker (server) MUST be uni-directional.

As I do not understand the purpose of your bi-directional dependencies, I do not exactly know how I could help you, unfortunately. Let me mention that the Cloud Controller is not designed in a way that would allow to update a service-instance that has an operation in progress with the broker managing this instance. In such a case, you must expect unexpected behavior. You see what I mean?

**Comment by kamath-prasad** [comment] 2017-05-17 15:05
**As I do not understand the purpose of your bi-directional dependencies, I do not exactly know how I could help you, unfortunately.**

Ans : As mentioned in my earlier comment , we have such dependency because during every code release we make , we update the service's ( vms's) with latest fixes/features using bosh . Since this takes place in the background and during this process any actions of 'cf update-service` by the cf developer can cause inconsistencies , we lock the service instance by explicitly making a PUT call to the cloud controller on each service instance that undergoes such background update. This way we use cloud controller's locking mechanism . If such approach is not correct/good , can you please guide us how such an activity is/should be performed for services to propagate fixes/features into the VM's  corresponding to the service instances?

Can you please point me to the specification which says the dependency between broker and CC must be Unidirectional ?We have this setup since a long time and it worked without any issues till we encountered this.

**Comment by nicregez** [comment] 2017-05-17 15:45
OK, so this is a misunderstanding from my side. You are not calling CC from the service broker, but rather from a function that is executed during a bosh deployment. That is, of course, absolutely fine and legitimate. Sorry for that!
So my next question: The unusable service instances, i.e. those for which the cloud controller do not poll the broker for their status after an Update has been triggered by the user, could their unexpected behavior somehow be related to the bosh deployments of the service VMs? For example, is there some deployment going on after the instances were created and before they get updated by the user?

**Comment by kamath-prasad** [comment] 2017-05-17 16:00
**OK, so this is a misunderstanding from my side. You are not calling CC from the service broker, but rather from a function that is executed during a bosh deployment. That is, of course, absolutely fine and legitimate.** 

Ok cool . 

**The unusable service instances, i.e. those for which the cloud controller do not poll the broker for their status after an Update has been triggered by the user, could their unexpected behavior somehow be related to the bosh deployments of the service VMs? For example, is there some deployment going on after the instances were created and before they get updated by the user?**

As mentioned above , the update was not triggered by the user but by the flow - 

( Our service management API made a HTTP PUT to CC with the parameter 'service-fabrik-operation' ) --> ( CC made a HTTP PATCH on service broker , with the parameter 'service-fabrik-operation' ) ---> ( Triggered the Update of Bosh Deployment )

For the service instances which encountered the error , there were no other actions taking place in the bosh layer . Also the PATCH call made by the CC to broker actually triggered the update in bosh deployment for all these service instances and it was completed successfully too.

**Comment by tcdowney** [comment] 2017-05-18 02:04
Hi @kamath-prasad, @ericpromislow and I were looking into this issue today.  We still have some additional investigation to do before we confirm a root cause, but first I'd like to clarify something.

You mentioned earlier that you did not see any Cloud Controller logs around this, but just to confirm, did you look at any of the Cloud Controller Worker logs?  The service state polling performed by Cloud Controller occurs in a [background job](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/services/service_instance_state_fetch.rb) so there is a chance that any failures could be in those logs and not with in the general CC API server logs.  These logs would contain the string: `cc-background` as their type.  If you do happen to find anything that would be very helpful.

Thanks!

**Comment by kamath-prasad** [comment] 2017-05-18 07:45
@tcdowney : No , we did not check the Cloud Controller Worker logs . Unfortunately we do not save logs for more than 10 days in this landscape and since this issue occurred during the last week of April , I cannot get this information for you.

**Comment by tcdowney** [comment] 2017-05-18 16:06
@kamath-prasad, that's okay.  Thanks for checking!  Our working theory is that some error occurred on the worker causing the `ServiceInstanceStateFetch` to fail and it wasn't retried successfully.  We'll keep you posted as we find out more.

**Comment by tcdowney** [comment] 2017-05-18 22:05
We were able to reproduce the situation described above locally by forcing the `ServiceInstanceStateFetch` to fail and observed that no additional polling took place.  We still need to come up with long-term fix that ensures the cloud controller continues to poll the service broker.

If you're comfortable with interacting with the CCDB, here's a one-time workaround that you could attempt to get your service instances back into operation.

1. Get the GUIDs of each affected service: `cf service <service name> --guid`
1. Bosh ssh on to the Cloud Controller api vm
1. Run the console script: `/var/vcap/jobs/cloud_controller_worker/bin/console`
1. Find the service instance: `service_instance = ManagedServiceInstance.find(guid: 'GUID')`
1. Set the service instance's last_operation to `'succeeded'`: `service_instance.update_last_operation(state: 'succeeded')`
1. Test out your service instance and repeat for all of the others if things look ok

Please keep in mind that we rarely advocate interacting directly with the database, as the schemas and fields are subject to change. But in this case, there is currently no way to do this with the `cf` command-line or API.

Let us know if you have any questions.

- @tcdowney and @ericpromislow

**Comment by tcdowney** [comment] 2017-05-18 22:20
We've created a bug in our Tracker for this issue:
https://www.pivotaltracker.com/story/show/145726645

**Comment by kamath-prasad** [comment] 2017-05-22 08:34
@tcdowney : Thanks for providing the details . To move ahead with our work , we had directly made the change in CCDB to fix those service instances - `update service_instance_operations set state='succeeded' where state='in progress'`

We will be watching the bug in tracker from now .

Just to check , once you provide the fix , we need to update the CF bosh release correct ?

**Comment by zrob** [comment] 2017-05-22 18:06
I would prefer we continue using this issue to track this for visibility to other folks in the community that may hit the same issue.  Please refer to the initial story linked by cf-gitbot for tracking progress.

**Comment by kamath-prasad** [comment] 2017-06-16 06:41
@tcdowney : Can you please let us know by when we will get a fix for this issue ?

**Comment by mikexuu** [comment] 2017-07-06 17:29
Hey @kamath-prasad,

Thanks for your logs. We took a look and we noticed that in the error log the request is being made to a *different* broker for a *different* service_instance guid. We are a bit confused how this relates to the service instance update problem for the first service_instance. 

In regards to @tcdowney's comment above on `ServiceInstanceStateFetch` retries, we took another look at the [background job](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/services/service_instance_state_fetch.rb) and it should rescue all types of errors -> errors are raised [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/services/service_brokers/v2/http_client.rb#L141) and rescued [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/services/service_instance_state_fetch.rb#L26). 
As a result, we think that the `ServiceInstanceStateFetchJob` is correctly getting re-enqueued for retries, but it takes a [default of 1 week](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/spec#L559-L561) for the job to finally mark the service instance `update operation` as `failed`. We would be interested to see if a service instance that looks stuck in the `update in progress` state eventually becomes a `failed` state after 7 days.

Another way to verify that the polling is being retried would be to look at your `delayed_jobs` table. If the polling job records are not in the table, then the job successfully completed. Therefore, if the state of the service instance is still stuck in `update in progress` state, it might be stemming from a different issue. 

Thanks, and let us know if you have any other questions.
@mikexuu & @anniesing

**Comment by kamath-prasad** [comment] 2017-07-10 11:57
@mikexuu 

> Thanks for your logs. We took a look and we noticed that in the error log the request is being made to a different broker for a different service_instance guid. We are a bit confused how this relates to the service instance update problem for the first service_instance.


-->We think that this issue with instances stuck in "Update in Progress" is not related to the error of another service broker. I had just mentioned this to let you know so that if you see any relationship with such a scenario in the CC code.

> In regards to @tcdowney's comment above on ServiceInstanceStateFetch retries, we took another look at the background job and it should rescue all types of errors -> errors are raised here and rescued here.
> As a result, we think that the ServiceInstanceStateFetchJob is correctly getting re-enqueued for retries, but it takes a default of 1 week for the job to finally mark the service instance update operation as failed. We would be interested to see if a service instance that looks stuck in the update in progress state eventually becomes a failed state after 7 days.

> Another way to verify that the polling is being retried would be to look at your delayed_jobs table. If the polling job records are NOT in the table, then the job either completed or errors are being properly rescued. In this case, we expect the update in progress to be set to either success or failed at the end of 7 days. If there IS a polling job record in the table, then the job failed to complete, and we were unable to rescue error X. In this case, we would need a more robust error rescuing logic. (searching logs for There was an error while fetching the service instance operation state would help determine what error type). Please let us know what you see!

---> We had a look at delayed_jobs table . We do not see any records for the service instances that we observed were stuck in progress . However there are many records in this table that are older than 7 days , infact we have records greater than 1 month old too but they have a valid updated_at or failed_at date populated.

Does this table delete records when we perform the steps mentioned in https://github.com/cloudfoundry/cloud_controller_ng/issues/817#issuecomment-302554470 i.e we manually update the status ?

I think to do more analysis on this issue , we must encounter it again and look into this table as well.

**Comment by kamath-prasad** [comment] 2017-08-01 10:17
@mikexuu & @anniesing 

Can you please share some updates on this issue ?

We faced this issue again in our landscape however this time the scenario is slightly different as mentioned below :

- We performed a `cf update-service <instance name> -p <new plan name>`
- The request came to the broker and it processed it . The broker also sent a HTTP 202 to the CC .
- The CC then polled for last operation , the broker responded with HTTP 200 since the update went through successfully .
- The CC still kept the status as "Update in progress" and keeps polling for last operation .

So in this scenario unlike the one mentioned above , CC is pinging the broker for last operation but does not update the status in CC .

**Comment by ljfranklin** [comment] 2017-08-31 23:47
@kamath-prasad apologies for letting this sit for so long. In your last [set of logs](https://github.com/cloudfoundry/cloud_controller_ng/issues/817#issuecomment-308946625) there are a couple things that jump out. From the router logs we see that the initial `PUT /v2/service_instances/ef2a7e3c-edb2-4938-b81d-5a370560cc42?accepts_incomplete=true` returned a `502`. CC should immediately return a 202 and begin polling. Since CC returned a 502 instead, polling never started. Also of interest is that PUT request took `342.026459138` seconds.

Could you share the all logs that contain that `vcap_request_id`: `95c3effc-dbd9-4e27-4d90-f86630670602`? This would help us uncover why the initial PUT request to CC failed. Again, apologies if the logs have already rotated out.

**Comment by kamath-prasad** [comment] 2017-09-01 04:50
@ljfranklin : Thanks for your response . Unfortunately we do not have the logs now as they are rotated every 15 days .  I can get it if we come across this issue again . Only hint I can give you is that the landscape where we experience this issue has huge load especially on the BOSH director . Although CF is only a BOSH deployment and should not interact with BOSH for its internal logic , just to check does CF have anything to do with BOSH director when it processes requests ?

**Comment by ljfranklin** [comment] 2017-09-01 14:52
> I can get it if we come across this issue again

@kamath-prasad thanks, we'll also try to be more timely in asking for logs next time.

> does CF have anything to do with BOSH director when it processes requests ?

Nope, the Cloud Controller makes no requests to the BOSH Director at any time.

**Comment by kamath-prasad** [comment] 2017-09-04 12:06
@ljfranklin  : we are again experiencing the issue mentioned here - https://github.com/cloudfoundry/cloud_controller_ng/issues/817#issuecomment-319330204

We are observing that the CC is still polling for last operation even if the broker has returned back HTTP 200 . 

In cloud controller logs , I see the following lines repeatedly : 

`2017-09-04T12:02:36.261104+00:00 10.0.129.71 vcap.cloud_controller_ng [job=api_z2 index=3]  {"timestamp":1504526556.2610137,"message":"Started GET \"/v2/security_groups?q=name%3Aservice-fabrik-0b0fdcbb-1d56-43a9-b89d-7c2ad1104605\" for user: 37964fd8-a234-4c04-af31-c3fe5e477bed, ip: 52.59.62.248 with vcap-request-id: 92ed85d8-c664-40e8-57bf-0e5059cbe29b::8dfeca7e-2185-4c3d-a427-dc910a5a9166 at 2017-09-04 12:02:36 UTC","log_level":"info","source":"cc.api","data":{"request_guid":"92ed85d8-c664-40e8-57bf-0e5059cbe29b::8dfeca7e-2185-4c3d-a427-dc910a5a9166"},"thread_id":46940595038080,"fiber_id":46940601855640,"process_id":5505,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_logs.rb","lineno":12,"method":"call"`

**Comment by Gerg** [comment] 2017-09-06 22:10
@kamath-prasad What response body is the broker returning to `GET /v2/service_instances/:instance_id/last_operation`? 

Do you see any logs in the cc worker with the message "There was an error while fetching the service instance operation state"

**Comment by kamath-prasad** [comment] 2017-09-12 14:48
@Gerg : 

> What response body is the broker returning to GET /v2/service_instances/:instance_id/last_operation?

Broker returns the following response body : 
```
  { state: 'succeeded',
     description: 'Update deployment service-fabrik-1120-904c4039-3acc-4bbe-b606-9a6358500b02 succeeded at 2017-09-12T14:06:24.000Z' } 
```

> 
Do you see any logs in the cc worker with the message "There was an error while fetching the service instance operation state"

Yes , I see many errors with this message : 

`<11>2017-09-12T14:06:26.723277+00:00 10.0.129.76 vcap.cloud_controller_ng [job=api_worker_z2 index=2]  {"timestamp":1505225186.7232122,"message":"There was an error while fetching the service instance operation state: service_plan paid_services_not_allowed_by_quota","log_level":"error","source":"cc-background","data":{"request_guid":"ef0b6fdc-ab52-48f3-763e-b5579aed3193::f0dc866a-86f0-4317-bd21-306b86be5518"},"thread_id":47081205281040,"fiber_id":47081244235720,"process_id":10151,"file":"/var/vcap/data/packages/cloud_controller_ng/3dfa085c5bf05a3cfbfe6b6d0defcc081a10d6b9/cloud_controller_ng/app/jobs/services/service_instance_state_fetch.rb","lineno":28,"method":"rescue in perform"}`

**Comment by ljfranklin** [comment] 2017-09-12 19:10
@kamath-prasad The `paid_services_not_allowed_by_quota` error means the organization that the service belongs to does not allow paid services and the service you are trying to update is marked as `free: false`.

Does your organization allow paid services? You can check with `cf org YOUR_ORG_NAME` which will list the current quota for your org. Then `cf quota YOUR_ORG_QUOTA` which should say `Paid service plans     allowed`.

If your org does not allow paid plans, then the next question is why did the validation occur at fetch state time rather when the initial update request was received. Did the org quota get updated to disallow paid plans between when the service instance was created and when the instance was updated by the broker?

**Comment by ljfranklin** [comment] 2017-09-12 19:17
Also to make sure we're on the same page, I tried to type up the order of events based on the above comments and logs:

Happy path
- Operator deploys service broker
- Users create service instances
- Operator wants to lock service instances from user modification while deploy is underway
- In order to prevent modifications to the instances, the Broker updates every service instance to make it look like a modification is underway
  - PUT /v2/service_instances/INSTANCE_GUID?accepts_incomplete=true
  - Request Body : { parameters : { 'service-fabrik-operation' : 'URL Encoded string'} }
- CC makes a PATCH call to the broker to let it know the user wants to update the instance
- Broker responds to CC with:
  - { operation: 'BASE64 ENCODED STRING' }
  - decoded:  {
                 taskId : 1234,
   	             type: 'update',
   	            'service-fabrik-operation' : 'URL Encoded string'
     }
- CC polls Broker until instance finishes updating and Broker returns "update succeeded"

Sometimes this works, but sometimes instances get stuck in "Update in progress" state
- Broker contacts CC to do an async update of the service instance
- CC contacts the broker to update the service
- Broker responds that it is updating the service instance
- CC fails to poll and update service state even though Broker would return a successful response
- Logs include many occurrences of "There was an error while fetching the service instance operation state: service_plan paid_services_not_allowed_by_quota"

**Comment by kamath-prasad** [comment] 2017-09-13 07:17
@ljfranklin  : Thanks for your response !!

 Please see my comments below : 

1. Based on your comment https://github.com/cloudfoundry/cloud_controller_ng/issues/817#issuecomment-328952126 , I check that the org in which these service instances were updated do not have quota enabled for paid service plans . Hence we were facing the issue . Also as you have mentioned even I am not sure how the service instances were created at the first place in that org , have asked the org owner to provide details . But on a side note , I think CC needs to error out when we try to update the service instance in such cases instead of proceeding with the update and leaving the instance in update in progress state.

2. Let me clarify the 2 issues which are tracked in the long list of comments : 

- The original issue was raised because of https://github.com/cloudfoundry/cloud_controller_ng/issues/817#issue-226586302 in which we see that instances are stuck in "Update in Progress" state since CC does not ping for last operation. This needs further investigation and fix from CC team .

- Then in a few days we started observed another issue https://github.com/cloudfoundry/cloud_controller_ng/issues/817#issuecomment-319330204 in which case , since the org does not have quota enabled for paid-services , CC was keeping the instance status as "Update in Progress" even after broker sends a HTTP 200 for last Operation .  We will find out why/how the instance got created in such org and CC team needs to handle this in such a way that update should error out in the beginning .

Let me know in case you need any further details .

**Comment by ljfranklin** [comment] 2017-09-13 16:14
@kamath-prasad agreed that there is a missing validation. We either need to validate the service instance when you update it or even when you switch your org's quota from paid to non-paid. I think the "Stuck in Update in Progress" issue is just a symptom of this missing validation but we'll keep an eye out to see if we could improve the async process.

**Comment by charleshansen** [comment] 2018-03-20 21:42
We just added the missing validation https://github.com/cloudfoundry/cloud_controller_ng/commit/91c4471fae5b504f909933e824db6dc5a7c52ac1

**Closed** 2018-03-21 22:49 UTC
Labels: PM Review, unscheduled
