### ISSUE TITLE
/v2/domains result: wrong "next_url"

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cloud_controller_ng#1108] opened 2018-03-08 16:03 UTC
## Issue

If you query `/v2/domains` you get a response with an invalid "next_url". The URL contains `order-by=internal` which is not allowed as sorting parameter.

## Context

[cf-deployment v.1.14.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v1.14.0)

## Steps to Reproduce
```
cf curl "/v2/domains?results-per-page=1"
{
   "total_results": 2,
   "total_pages": 2,
   "prev_url": null,
   "next_url": "/v2/domains?order-by=internal&order-direction=asc&page=2&results-per-page=1",
   "resources": [
      {
         "metadata": {
            "guid": "b8b61ded-8976-4395-ac0b-ea7a2c0ebc10",
            "url": "/v2/shared_domains/b8b61ded-8976-4395-ac0b-ea7a2c0ebc10",
            "created_at": "2018-02-26T12:03:18Z",
            "updated_at": "2018-02-26T12:03:18Z"
         },
         "entity": {
            "name": "<redacted>",
            "router_group_guid": null,
            "router_group_type": null
         }
      }
   ]
}

cf curl "/v2/domains?order-by=internal&order-direction=asc&page=2&results-per-page=1"
{
   "description": "Cannot order by: internal",
   "error_code": "CF-OrderByParameterInvalid",
   "code": 10012
}
```
## Expected result

"prev_url" and "next_url" should be valid URLs for subsequent CC requests.

## Current result

See above: You get an error 500 when using the prev/next URL.

**Comment by Gerg** [comment] 2018-03-19 22:16
Hey @jochenehret 

I believe this is a duplicate of https://github.com/cloudfoundry/cloud_controller_ng/issues/1112. Closing for now, please re-open if I am mistaken

Thanks,
@gerg

**Closed by Gerg** 2018-03-19 22:16 UTC
Labels: unscheduled
