### ISSUE TITLE
Don't call /v3/processes/PROCESS_GUID/stats  for zero-instance processes

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#1946] opened 2020-11-05 20:44 UTC
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

I pushed the spring-petclinic, which ends up with 3 processes, web has 1 instance, `executable-jar` and `task` have 0.

## Context

[provide more detailed introduction]

## Steps to Reproduce

```
z spring-petclinic
cf push petclinic
PROCESSES_LINK=$(cf curl /v3/apps?names=petclinic1 | jq -r '.resources[0].links.processes.href')
cf curl $PROCESSES_LINK  | jq -r '.resources[] | [.type, .links.stats.href]' | sed 's@.*/v3@/v3@'
```
gives three pairs of `(process-type, stats-link)` pairs.

```
$ time cf curl /v3/processes/2c61e89b-dca1-4573-b95e-0691c69dce68/stats
{
  "resources": [ { ... actual data } ]
}
real	0m0.689s
user	0m0.056s
sys	0m0.041s

$ time cf curl /v3/processes/b060fe3a-03d9-45b4-a2f3-46db1a08e07d/stats
{
   "resources": []
}

real	0m5.441s
user	0m0.052s
sys	0m0.038s

$ time cf curl /v3/processes/2fe0d913-4d18-4078-8d10-bcdc85a5a4d7/stats
{
   "resources": []
}

real	0m5.444s
user	0m0.055s
sys	0m0.040s
```
## Expected result

The exact same output, but with much smaller real/user/sys times for the second two curl calls

## Current result

painful waits for `cf apps`

## Possible Fix

If a process has zero instances, immediately return `(200, { "resources": [] })`

**Comment by Gerg** [comment] 2020-11-05 23:10
@ericpromislow I wasn't able to reproduce this using cf-deployment:

```
$cf curl /v3/apps/`cf app dora --guid`/processes | jq '.resources[] | (.guid, .instances)'
"c163959f-6a6d-428c-9c4c-4ef892f644a8"
1
"ebcd4c88-a28e-4236-8de2-3451d75aa9fd"
0
```
```
$ time cf curl /v3/processes/c163959f-6a6d-428c-9c4c-4ef892f644a8/stats > /dev/null

real	0m0.429s
user	0m0.047s
sys	0m0.075s
```
```
$ time cf curl /v3/processes/ebcd4c88-a28e-4236-8de2-3451d75aa9fd/stats > /dev/null

real	0m0.212s
user	0m0.049s
sys	0m0.047s
```

I suspect this might only be an issue in cf-for-k8s.

**Comment by ericpromislow** [comment] 2020-11-06 20:48
Is this a diego vs eirini issue?

What was the text that the calls to the second process returned?

There is a PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/1934/files

**Comment by sethboyles** [comment] 2021-02-22 20:10
@ericpromislow that PR has been merged.  Has that resolved your issue?

**Comment by sethboyles** [comment] 2021-12-09 01:11
closing due to lack of response

**Closed by sethboyles** 2021-12-09 01:11 UTC
Labels: bug, unscheduled, k8s
