### ISSUE TITLE
In /v3/apps request the selector does not handle spaces within 'in' blocks

### ISSUE THREAD

**Issue by JenGoldstrich** [cloudfoundry/cloud_controller_ng#1443] opened 2019-09-13 18:36 UTC
## Issue

When querying /v3/apps with a label selector, if we have a space in the middle of an in block in our selector, we see a failure

Example: 

```
a in (b, c)
```
)

We receive a 400 error, however if we do

```
a in (b,c)
```

It works as expected
## Context

Based on the k8s documentation we expect that spaces would be ignored in the in block
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement

## Steps to Reproduce

1.) Be authenticated to use v3 API
2.) Run query with label selector to /v3/apps 
```
(for example '/v3/apps?label_selector=environment%20in%20(production,%20staging)
```
3.) See error message

## Expected result

1.) Be authenticated to use v3 API
2.) Run query with label selector to /v3/apps 
```
(for example '/v3/apps?label_selector=environment%20in%20(production,%20staging)
```
3.) See list of apps where label environment is set to production or staging

## Current result

```cf curl '/v3/apps?label_selector=environment%20in%20(production,%20staging),tier%20in%20(backend)' ```

```{
   "errors": [
      {
         "detail": "The query parameter is invalid: ' staging' contains invalid characters",
         "title": "CF-BadQueryParameter",
         "code": 10005
      }
   ]
}
```
logs:
```
`invalid_param!'\", \"/var/vcap/data/packages/cloud_controller_ng/07191044471d4ef2c8bd8576d78b11c8b00f0c8b/cloud_controller_ng/app/controllers/v3/apps_controller.rb:39
```

## Possible Fix

ignore white-space around keys

**Comment by cwlbraa** [comment] 2019-09-13 21:58
closing this as duplicate of https://github.com/cloudfoundry/cloud_controller_ng/issues/1444 because that's a superset of this one.

**Closed by cwlbraa** 2019-09-13 21:58 UTC
Labels: unscheduled
