### ISSUE TITLE
Retrieve a Particular Service Instance's Parameters doesn't work as expected

### ISSUE THREAD

**Issue by s-matyukevich** [cloudfoundry/cloud_controller_ng#1292] opened 2019-02-05 16:49 UTC
## Issue

I was considering writing a CF CLI backup/restore plugin. The plugin should iterate over all applications, store their configuration as well as service instance configuration. I discovered that [this](https://apidocs.cloudfoundry.org/7.2.0/service_instances/retrieve_a_particular_service_instance_parameters_experimental.html) api call doesn't work

## Context

Details can be found [here](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/issues/26)

## Steps to Reproduce

```
cf curl /v2/service_instances/<service-instance-id>/parameters
```

## Expected result

JSON with parameters

## Current result

Error "not supported"

## Possible Fix

Instead of reaching out to brokers to retrieve current parameters we can store the parameters in cloud controller database. If there were multiple calls to the `update-service` command we can merge provided JSON files. We can also provide the list of JSON objects that were used in all `update-service` commands in the response of the `Retrieve a Particular Service Instance's Parameters` api call

**Comment by nmaslarski** [comment] 2019-02-06 12:35
Hay,
Currently the cloud controller relies on the broker to provide this information.
We return `CF-ServiceFetchInstanceParametersNotSupported` if "instances_retrievable" is set to false in the services broker catalog for the current service.

About the proposed fix:
CC doesn't use the parameters for anything hence we're not storing them right now.
@laurzca @mattmcneeney @williammartin

**Comment by williammartin** [comment] 2019-02-18 13:52
Hey @s-matyukevich,

Unfortunately, I don't think your suggestion is possible (at least right now with the current OSB API specification). 

It is up to service brokers to determine whether they will support fetching of parameters. The reason this is the case is that brokers can provide out-of-band reconfiguration, for example, via a service instance's dashboard. The risk of storing parameters in the CC is that we could get out of sync with the actual state.

We could consider trying to get a change into the specification such that brokers can indicate that platforms should store this information, and they won't be sneakily changing parameters behind the scenes, but this would also require a change to brokers (we wouldn't want to change the default behaviour). It may provide a lower barrier for broker authors to provide parameters though.

What do you think? Do you have any other ideas?

**Comment by s-matyukevich** [comment] 2019-02-21 15:48
Thanks @williammartin !

This sounds reasonable - if we allow out-of-band broker configuration there is no way how we can implement this functionality without changing existing brokers. However we probably can minimize broker changes in the following way: in the broker specification we can say that the broker must implement retrieve-service-instance-parameters method only if this broker supports out-of-band configuration. If a broker doesn't support such configuration (and I believe this is the case for the majority of the brokers) the broker authors don't have to make any changes to the broker code.
Cloud controller then can first ask broker for the parameters, and if the broker responds with non 200 status code return parameters stored in the CC database.

I think this would make sense because adding additional method to the brokers to retrieve service instance parameters was the direction we were heading anyway, right?

Also if we consider the use-case for this functionality (a CLI plugin that implements backup/restore functionality using CC API) the consequences of getting out of sync with the actual broker state are rather low:  in the plugin documentation we can highlight the fact that the plugin is going to work correctly only with the brokers that satisfy the latest broker specification. If you are using a broker that allow out-of-band configuration and doesn't implement retrieve-service-instance-parameters method, your manually configured parameters can be overwritten after the restore. (which I believe is not a huge deal either because most PCF customers use CI/CD pipelines to push their apps and never use service dashboards to configure service instances)

**Comment by williammartin** [comment] 2019-02-21 16:22
Thanks for your response. Unfortunately I don't think that your proposal is something we can get into the specification. I appreciate your consideration of reducing work for broker authors but unfortunately, we're not able to get anything into the specification (without a major version bump) that _requires_ broker authors to change anything (i.e. no new `MUST`s unless they are hidden behind a `SHOULD` or `MAY`).

I'm just going to restate what I think your proposal is, in case I misunderstood. I think there are two cases you are suggesting:

```
If fetch returns non-200 endpoint on fetch then:
 Return parameters that the service instance was created with (and cached on creation)
Else
  Return those parameters

Brokers who want to support out of band configuration (i.e non-200) MUST support fetching.
```

If I understand this correctly, the problem is that there will be a breaking change for brokers that support OOB communication but don't currently support fetch.

We could take a step back and consider what the implications are of being able to fetch parameters that services were created with, and how this might solve the majority of your use cases as you suggest.

**Comment by s-matyukevich** [comment] 2019-02-21 17:29
Yes, you restated my proposal correctly. What if we restate that and say that "Brokers who want to support out of band configuration  SHOULD support fetching."? Anyway no existing functionality is going to be broken.

**Comment by williammartin** [comment] 2019-02-22 13:52
Yes so we probably could get that kind of wording into the spec but let's circle back to the problem we're trying to solve here and what implications there might be for others.

I'm going to restate what I think you're trying to do (your explanation on the other issue was great), just to make sure we're aligned again. I think that as part of writing a plugin for backup and restore, you want to ask Cloud Foundry "tell me about all the service instances, and tell me details about them so that when I restore, I can ask the broker to create similar shaped instances again".

And your request is that CF should give you:
1. The latest parameters that a service instance is configured with
2. The parameters that a service instance was created with, in case the broker doesn't support 1.

You think that having out of date parameters is an acceptable trade off for most PCF customers because they probably don't ever configure out of band since they use pipelines?

Is that all correct?

If so, I have a few comments, firstly:

```
in the plugin documentation we can highlight the fact that the plugin is going to work correctly only with the brokers that satisfy the latest broker specification.
```

To be clear, it is not required for brokers to implement fetching a service instance to be compatible with the spec. It is a `SHOULD`. Additionally, it is not required that brokers implementing fetching a service instance return all configuration parameters as they may want to keep some as secrets.

Secondly:

```
(which I believe is not a huge deal either because most PCF customers use CI/CD pipelines to push their apps and never use service dashboards to configure service instances)
```

This may be true, but we also need to consider how this feature might be used by others. I can see some real confusion stemming from asking the API "what configuration parameters does this instance have" giving out of date information. Perhaps there's some way we can indicate on any response that parameters might be out of date.

Finally, since brokers currently have control over what parameters they might return (e.g. not returning secrets), I'm concerned about the CC caching these. We could update the spec such that broker authors have to specifically mark parameters that are acceptable to store, but then we're back to square one with broker author's having to do things.

Fun!

**Comment by s-matyukevich** [comment] 2019-02-25 20:38
@williammartin 

Regarding your first comment
```
To be clear, it is not required for brokers to implement fetching a service instance to be compatible with the spec. It is a `SHOULD`. Additionally, it is not required that brokers implementing fetching a service instance return all configuration parameters as they may want to keep some as secrets.
```
 In the plugin documentation we can explicitly specify what  is needed from the brokers in order for backups to work. Probably we can do the same in the fetch parameters API call documentation. Adding a warning to the fetch parameters response, in case when there is a possibility that the call can return stale parameters, is a good idea as well.

Regarding your second comment:
```
This may be true, but we also need to consider how this feature might be used by others. I can see some real confusion stemming from asking the API "what configuration parameters does this instance have" giving out of date information. Perhaps there's some way we can indicate on any response that parameters might be out of date
```
I agree with that. Though I think that warning in the API call documentation + similar warning in the API response should resolve that issue.

```
Finally, since brokers currently have control over what parameters they might return (e.g. not returning secrets), I'm concerned about the CC caching these. We could update the spec such that broker authors have to specifically mark parameters that are acceptable to store, but then we're back to square one with broker author's having to do things.
```
If we allow brokers to hide some of the parameters the whole idea of backing up the platform using API looses any sense, because we must know all parameters in order to accurately reproduce the deployment. I would rather solve this issue by introducing proper access rights to the API call (we may consider allowing this API call only to somebody with "cloud_controller.admin" uaa scope) + we can encrypt the value in the database if that is necessary for additional security.

**Comment by williammartin** [comment] 2019-04-18 09:24
We've passed this discussion on to some of the desired broker's teams for now to implement fetching of parameters correctly. Closing now but happy to reopen for more discussion from you or others.

**Closed by williammartin** 2019-04-18 09:24 UTC
Labels: sapi, unscheduled
