### ISSUE TITLE
'cf delete-shared-domain' crashes api_worker

### ISSUE THREAD

**Issue by jsievers** [cloudfoundry/cloud_controller_ng#694] opened 2016-10-07 14:04 UTC
## Issue

`cf delete-shared-domain`

on a Cloudfoundry deployment with ~1500 apps which have a route associated with that domain seems to hang forever on the client side.
Looking into the monit logs on the api_worker processing the delayed job, we found that monit continuously restarted the cloud_controller_worker_1 process. Using htop we saw that the process was eating up more and more memory. The restart would happen many times in a row until the job scheduler would give up. 

We even tried changing the max memory threshold in the monit script from 512m to 2048m, same result.
## Context
- Using Cloudfoundry v240
- we were moving our default domain to a new domain
- in this process, we added new routes to all apps and then tried to delete the old domain using

`cf delete-shared-domain <OLD_DOMAIN>` 
- We relied on the above statement to delete all associated routes.
- As a workaround, we deleted all routes one by one, then delete-shared-domain would succeed.
## Steps to Reproduce

you need a cloudfoundry deployment with ~1500 apps/routes associated with a shared domain.
Maybe even less is sufficient to reproduce as we quadrupled max mem and still saw the process being killed due to too much memory consumed.
## Expected result

`cf delete-shared-domain` should succeed and delete all associated routes.
## Current result

Takes more than 20 minutes, then crashes with "unexpected error" on the client side. Also api_worker logs below.
## Possible Fix

?

cloud_controller_worker_ctl.log snippet:

```
[2016-10-06 11:12:13+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=1162347) RUNNING
[2016-10-06 11:14:03+0000][2016-10-06 11:14:03+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Exiting...
 Killing /var/vcap/sys/run/cloud_controller_worker/cloud_controller_worker_1.pid: 11686
[2016-10-06 11:14:34+0000] Kill timed out, using kill -9 on 11686
[2016-10-06 11:14:34+0000] Stopped
[2016-10-06 11:14:44+0000] ------------ STARTING cloud_controller_worker_ctl at Thu Oct  6 11:14:44 UTC 2016 --------------
[2016-10-06 11:14:49+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Starting job worker
[2016-10-06 11:14:49+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=1162347) RUNNING
[2016-10-06 11:16:45+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Exiting...
[2016-10-06 11:16:45+0000] Killing /var/vcap/sys/run/cloud_controller_worker/cloud_controller_worker_1.pid: 14416
[2016-10-06 11:17:16+0000] Kill timed out, using kill -9 on 14416
[2016-10-06 11:17:16+0000] Stopped
[2016-10-06 11:17:26+0000] ------------ STARTING cloud_controller_worker_ctl at Thu Oct  6 11:17:26 UTC 2016 --------------
[2016-10-06 11:17:31+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Starting job worker
[2016-10-06 11:17:31+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=1162347) RUNNING
[2016-10-06 11:19:27+0000][2016-10-06 11:19:27+0000] Killing /var/vcap/sys/run/cloud_controller_worker/cloud_controller_worker_1.pid: 15030
 [Worker(cc_global_worker.api_worker_z1.0.1)] Exiting...
[2016-10-06 11:19:57+0000] Kill timed out, using kill -9 on 15030
[2016-10-06 11:19:58+0000] Stopped
[2016-10-06 11:20:08+0000] ------------ STARTING cloud_controller_worker_ctl at Thu Oct  6 11:20:07 UTC 2016 --------------
[2016-10-06 11:20:13+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Starting job worker
[2016-10-06 11:20:13+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=1162347) RUNNING
[2016-10-06 11:22:09+0000] Killing /var/vcap/sys/run/cloud_controller_worker/cloud_controller_worker_1.pid: 15622
[2016-10-06 11:22:09+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Exiting...
[2016-10-06 11:22:39+0000] Kill timed out, using kill -9 on 15622
[2016-10-06 11:22:40+0000] Stopped
[2016-10-06 11:22:49+0000] ------------ STARTING cloud_controller_worker_ctl at Thu Oct  6 11:22:49 UTC 2016 --------------
[2016-10-06 11:22:55+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Starting job worker
[2016-10-06 11:22:55+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=1162347) RUNNING
[2016-10-06 11:24:51+0000] Killing /var/vcap/sys/run/cloud_controller_worker/cloud_controller_worker_1.pid: 16212
[2016-10-06 11:24:51+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Exiting...
[2016-10-06 11:25:21+0000] Kill timed out, using kill -9 on 16212
[2016-10-06 11:25:21+0000] Stopped
[2016-10-06 11:25:31+0000] ------------ STARTING cloud_controller_worker_ctl at Thu Oct  6 11:25:31 UTC 2016 --------------
[2016-10-06 11:25:37+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Starting job worker
[2016-10-06 11:25:37+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=1162347) RUNNING
[2016-10-06 11:27:33+0000] Killing /var/vcap/sys/run/cloud_controller_worker/cloud_controller_worker_1.pid: 16811
[2016-10-06 11:27:33+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Exiting...
[2016-10-06 11:28:03+0000] Kill timed out, using kill -9 on 16811
[2016-10-06 11:28:04+0000] Stopped
[2016-10-06 11:28:13+0000] ------------ STARTING cloud_controller_worker_ctl at Thu Oct  6 11:28:13 UTC 2016 --------------
[2016-10-06 11:28:19+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Starting job worker
[2016-10-06 11:28:19+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=1162347) RUNNING
[2016-10-06 11:30:15+0000] Killing /var/vcap/sys/run/cloud_controller_worker/cloud_controller_worker_1.pid: 17400
[2016-10-06 11:30:15+0000] [Worker(cc_global_worker.api_worker_z1.0.1)] Exiting...
[2016-10-06 11:30:45+0000] Kill timed out, using kill -9 on 17400
[2016-10-06 11:30:46+0000] Stopped
```

**Comment by luan** [comment] 2016-12-06 21:50
Hi @jsievers,

We tried to reproduce this on our development environment by pushing 3000 apps with routes in a custom sheared domain. The deletion of that shared domain takes about 5s at most and goes very smoothly every time. We don't see anything pointing to failure in the logs and also we don't see memory usage spikes using top or looking at the monit metrics.

To help us better understand the issue, would you be able to provide all the logs from that cloud controller? We're particularly interested in the `cloud_controller_worker/cloud_controller_worker.log` and the `cloud_controller_ng/cloud_controller_ng.log` files.

We understand those may have things you might not want to share in public, so feel free to either redact any details in there or share them in private if you prefer.

Thanks,
@luan & @ericpromislow, CF CAPI Team

**Comment by jsievers** [comment] 2016-12-12 12:13
sorry but our log retention policy for these log files does not reach as far back as 2 months, so I'm afraid they are no longer available by now.

If it helps, this is the context: We were migrating a whole CF deployment with running apps from one default app domain to another. For this, we would

1. Change app_domains (and update SSL certs for load balancer) in the CF manifest to the new default app domain
2. Override directory keys (=S3 bucket names) for app-related binaries to keep values derived from old domain (resource_directory_key, buildpack_directory_key, app_package_directory_key, droplet_directory_key)
3. Migrate apps
run `cf domains` to get the old and new apps domains
run 

```./domain_migration.sh <OLD_APPS_DOMAIN> <NEW_APPS_DOMAIN> ```

(attached)
This script (1) gets a list of all apps, (2) gets their associated routes, (3) duplicates the route (if it contains the old domain; uses the new domain), and (4) maps the route to the app.
4. run `cf delete-shared-domain <OLD_APPS_DOMAIN>`

step 4. is where the failure described above occurred.

**Comment by thausler786** [comment] 2017-01-25 22:01
We apologize for not responding sooner when you had logs--responding in a timely manner to community issues is something we aspire to, but sometimes fall short at.  As we have been unable to reproduce this a second time, we are going to close this issue at this time.

If you see this again, make sure to capture the logs and reopen this issue and we'll look into it (hopefully more successfully the next time around).

Best
@thausler786 && @ljfranklin, CF CAPI team

**Closed by thausler786** 2017-01-25 22:01 UTC
Labels: unscheduled
