### ISSUE TITLE
Error filtering 'List All Service Plans' by service broker id

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#812] opened 2017-04-26 12:33 UTC
## Issue

The field `service_broker_guid` documented as a filter for [List All Service Plans](http://apidocs.cloudfoundry.org/253/services/list_all_service_plans_for_the_service.html) gives the error `CF-BadQueryParameter(10005): The query parameter is invalid: service_broker_guid`

## Steps to Reproduce

Perform a query as follows:

`cf curl /v2/services/<serviceId>/service_plans?q=service_broker_guid:test-id`

The following error is returned:
```
{
   "description": "The query parameter is invalid: service_broker_guid",
   "error_code": "CF-BadQueryParameter",
   "code": 10005
}
```

The same query without the filter gives something like:
```
{
   "total_results": 1,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
      {
         "metadata": {
            "guid": "5a51c7e0-8236-4790-89d5-921750bd2da9",
            "url": "/v2/service_plans/5a51c7e0-8236-4790-89d5-921750bd2da9",
            "created_at": "2017-04-26T12:06:05Z",
            "updated_at": "2017-04-26T12:06:06Z"
         },
         "entity": {
            "name": "test-plan-av9tt",
            "free": true,
            "description": "test-plan-description",
            "service_guid": "6b9c14f5-b9bb-437d-9648-5dd74d50af34",
            "extra": "{\"bullets\":[{\"content\":\"test-plan-metadata-bullet\"}],\"costs\":[{\"amount\":{\"usd\":1},\"unit\":\"MONTHLY\"}]}",
            "unique_id": "1480197f-2eac-436d-ab10-716d9d24cc20",
            "public": true,
            "bindable": true,
            "active": true,
            "service_url": "/v2/services/6b9c14f5-b9bb-437d-9648-5dd74d50af34",
            "service_instances_url": "/v2/service_plans/5a51c7e0-8236-4790-89d5-921750bd2da9/service_instances"
         }
      }
   ]
}
```
Note the absence of a `service_broker_guid` field, which makes me think it should be removed from the doc.

## Possible Fix

Remove `service_broker_guid` from the documentation (or enable as a filter, though that seems less likely!)

**Comment by ericpromislow** [comment] 2017-05-01 23:09
Duplicate of https://github.com/cloudfoundry/cloud_controller_ng/issues/788

Fixed in the docs for v255 (CC API Version 2.78.0)

**Closed by ericpromislow** 2017-05-01 23:09 UTC
Labels: in progress
