### ISSUE TITLE
Cloud controller crashes when primary mysql instance is shutdown

### ISSUE THREAD

**Issue by randomtask1155** [cloudfoundry/cloud_controller_ng#737] opened 2016-12-01 15:18 UTC
During CF upgrade when bosh restarts the primary mysql server instance Cloud controller workers will log mysql disconnect errors and cloud controller will restart causing a 20-30 second api outage.   It seems [sequel 4.29.0](https://github.com/jeremyevans/sequel/tree/4.29.0) does not handle the proxy disconnect very well.

## Repro steps tested in cf v235

- Ping API endpoint every one second

```
while true; do date; cf curl /v2/info ;sleep 1; done
```

- ssh into the primary mysql server instance and run `monit stop all` to shut it down

- mysql proxy will sever all client connections and failover to another mysql server instance

- Cloud controller will report the following errors and restart resulting in 502 gateway errors for api calls

```
{"timestamp":1480559458.0446959,"message":"Mysql2::Error: MySQL server has gone away: SELECT `queue`, count(*) AS `count` FROM `delayed_jobs` WHERE (`attempts` = 0) GROUP BY `queue`","log_level":"error","source":"cc.db","data":{},"thread_id":47119552608660,"fiber_id":47119598241500,"process_id":10703,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
{"timestamp":1480559459.874028,"message":"Mysql2::Error: MySQL server has gone away: SELECT * FROM `delayed_jobs` WHERE ((((`run_at` <= '2016-12-01 02:30:59') AND (`locked_at` IS NULL)) OR (`locked_by` = 'cc_api_worker.cloud_controller-partition-a6bab9c6d39df7a11717.0.2')) AND (`failed_at` IS NULL) AND (`queue` IN ('cc-cloud_controller-partition-a6bab9c6d39df7a11717-0'))) ORDER BY `priority` ASC, `run_at` ASC LIMIT 5","log_level":"error","source":"cc.background","data":{},"thread_id":47333164063120,"fiber_id":47333200040920,"process_id":10820,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
{"timestamp":1480559459.885567,"message":"Mysql2::Error: MySQL server has gone away: SELECT * FROM `delayed_jobs` WHERE ((((`run_at` <= '2016-12-01 02:30:59') AND (`locked_at` IS NULL)) OR (`locked_by` = 'cc_api_worker.cloud_controller-partition-a6bab9c6d39df7a11717.0.1')) AND (`failed_at` IS NULL) AND (`queue` IN ('cc-cloud_controller-partition-a6bab9c6d39df7a11717-0'))) ORDER BY `priority` ASC, `run_at` ASC LIMIT 5","log_level":"error","source":"cc.background","data":{},"thread_id":47067827304840,"fiber_id":47067871129900,"process_id":10769,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
{"timestamp":1480559479.1359675,"message":"db config {:database=>\"mysql2://c0a4914768f7692e5fb1:cdb06493db5159344ee2@10.193.72.18:3306/ccdb\", :max_connections=>25, :pool_timeout=>10, :log_level=>\"debug2\"}","log_level":"info","source":"cc.runner","data":{},"thread_id":47218227902860,"fiber_id":47218243388500,"process_id":24848,"file":"/var/vcap/data/packages/cloud_controller_ng/ff8f1323b6b25c063244cf8b75cae89431e0925a.1-6d8fadf5135424dd7270d64a117749d43247d514/cloud_controller_ng/lib/cloud_controller/runner.rb","lineno":172,"method":"setup_db"}
```

**Comment by thausler786** [comment] 2016-12-05 22:44
@randomtask1155,

We reproduced the error you described by shutting down our db for a few seconds and restarting it.  It turns out that there are some periodic metrics reporting tasks that this can fatally disrupt.  We added some logic to protect against that codepath taking down the CC in the future at this sha: 819b71803b41b66537f4a3e6448c2459de884486.

We are going to close this issue, if you feel like it has not been fixed or the behavior persists after this fix is applied please do not hesitate to reopen it.

Best,
@thausler786 && @luan, CAPI team members

**Closed** 2016-12-13 19:50 UTC
Labels: accepted

**Comment by thausler786** [comment] 2016-12-13 19:58
Closing this issue, please reopen if it persists!
