### ISSUE TITLE
Unable to update service instance from inactive plan to active plan

### ISSUE THREAD

**Issue by bar-jakubovitz** [cloudfoundry/cloud_controller_ng#493] opened 2016-01-10 08:19 UTC
Scenario :
1. Non admin user with space manager and developer roles.
2. Service's "plan_updateable" flag set to true
3. Service_instance created with plan-A (witch was later removed from the SB catalog, inactive plan)
4. Update service_instance to plan-B (available in catalog, active plan)

CLI request fail with error :
> FAILED
> Plan does not exist for the  service
seem the CC response is missing the service_plan_guid (returns null) and the service_plan section which contains the service guid.

Trying though direct curl to CC fails with :
> {
> "code": 10003,
> "description": "You are not authorized to perform the requested action",
> "error_code": "CF-NotAuthorized"
> }

**Comment by fkotsian** [comment] 2016-01-19 19:36
Hi @bar-jakubovitz! We're looking into your issue. We've attempted to reproduce, but some additional information would be helpful to make sure we got the exact scenario right. Could you tell us:

- is this service a user-provided service or a managed service?
- at what point was plan-A removed from the broker catalog? (between Steps 3 and 4, or after Step 4)?
- how was plan-A removed from the broker?

Thanks!

Frank && Kara
CF CAPI Team

**Comment by zrob** [comment] 2016-02-11 01:51
Hi @bar-jakubovitz 

We were able to reproduce your issue

**Comment by bar-jakubovitz** [comment] 2016-02-23 20:32
Hi, 
Sorry for the really really late response... the email got lost some place in my inbox.

* managed service.
* before step 4
* the catalog did not include it in the response after plan B was added, then I did a $cf update-service-broker to get plan B in the marketplace.

**Comment by dieucao** [comment] 2016-02-29 04:33
@bar-jakubovitz We've fixed this issue on the cloud controller side and the fix will be available in the next cf-release.
A change is still needed on the cf cli side to not fail the service plan update if the old service plan is not visible to the user due to it being de-activated.

@dkoper FYI

**Comment by dieucao** [comment] 2016-02-29 04:34
@bar-jakubovitz Please open an issue on the cf CLI to address the cf CLI issue.
Closing this issue on cloud controller.

**Closed by dieucao** 2016-02-29 04:34 UTC
