### ISSUE TITLE
CloudController loops opening and closing thousands of connections to NATs on an arbitrary error

### ISSUE THREAD

**Issue by krumts** [cloudfoundry/cloud_controller_ng#794] opened 2017-03-20 13:57 UTC
## Issue

We observed the following issue in our CloudFoundry installation:
When a problem occurs, which is in no way related to the nats connectivity (a concrete one was loosing the connection to the Postgres DB of CC), the cloud controller process falls into a state where it does nothing else but looping in opening a connection to the nats server(s) and then immediately closing it. The visible symptoms are very high CPU usage on both client and server side, kernel messages like "TCP: request_sock_TCP: Possible SYN flooding on port 4222. Sending cookies. Check SNMP counters." on the NATs server side, high network load (with lots of small packages, i.e. just the connection establishment) between the nats client and server.

## Context

I could see the CC ruby process looping, if an error (i.e. DB not running) happens within the run! method of runner.rb: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/runner.rb#L93 . Once this happens, the error is logged (line 95), then the process should exit, but it doesn't.

I managed to track this down to a problem between the ruby-nats client and EM: https://github.com/nats-io/ruby-nats/issues/138 . I added there a pretty detailed description of the issue and how I analyzed it. There is also already a fix in the ruby-nats client for it. Using the latest version (currently v0.8.2) should prevent such behavior in the CC.

I believe this is also the explanation of the high CPU usage in NATs, reported by https://github.com/cloudfoundry/cloud_controller_ng/issues/732. However, I open a new issue, as 732 seems to be more focused on the error handling. With the fix in ruby-nats the process will simply exit (without looping endlessly), which I think is also a reasonable reaction to the exception, as the process would be restarted by monit.

The interesting part however, is that CC uses a pretty old version of the ruby-nats library, and I am not sure if / how problematic an update to the latest release would be. The comment in the Gemfile
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/Gemfile#L47-L50 mentions that a version newer that v0.5.1 would be acceptable. However, the following commit https://github.com/cloudfoundry/cloud_controller_ng/commit/3b296debe09d222c6aa4f8a4244184cb14408015 reverts an attempt to update the nats client, and the commit was made in Oct 2016 - at this time the nats release should have been v0.8.0. Are there other reasons to stick to the older release? Is the update to v0.8.2 now possible?

## Steps to Reproduce

Stop the Posrtgres DB under the CC. After a while the ruby process will start using very high CPU. Use strace to see that the process is doing nothing but opening and closing of connections; use tcpdump to show that the connections are to NATs.

## Expected result

The CC process should either exit or handle the error somehow.

## Current result

The CC ruby process loops until it gets stopped by monit. If the issue (e.g. the connection to the DB not possible) still persists, the same situation repeats.

## Possible Fix

Using the latest version of ruby-nats (currently v0.8.2), containing the fix for https://github.com/nats-io/ruby-nats/issues/138 should solve the problem. With the fix, the CC process will simply log the error and exit. In case this is not the desired behavior, some reasonable handling of the errors should be implemented.

**Comment by ScarletTanager** [comment] 2017-03-20 14:25
Hi @krumts , my first instinct is that this is a duplicate of [Issue 732](https://github.com/cloudfoundry/cloud_controller_ng/issues/732), which also traces back to an issue with EM and error handling (with what sound like very similar symptoms).  @ericpromislow and I looked into 732 on Friday and think there is way to fix this in code, but can you take a look and see if you agree that they might be the same Issue?

**Comment by krumts** [comment] 2017-03-20 14:55
Hi @ScarletTanager , I had seen https://github.com/cloudfoundry/cloud_controller_ng/issues/732 before I created this one, and I am pretty sure that they both have the same cause, as I mentioned in my initial comment. However, there are two possible actions I see:
- add an error handler (and I thought this is the main focus of 732)
- use the fixed ruby-nats client version, so that the CC process doesn't end up looping in opening/closing connections to NATs.

The latter I find in any case useful, as using the fixed ruby-nats library will prevent the problem to appear also for code places, for which no error handler is provided. So my concrete request is to update to the latest ruby-nats release, and I saw that this has not been possible in the past.

I also wanted to give some more details on the route cause I identified. If you think it's better to have just one ticket, it is fine for me closing this one as a duplicate. I hope the details I added would be useful.

**Comment by ScarletTanager** [comment] 2017-03-20 15:03
HI @krumts , yeah, I think it would be better to have one ticket for the looping issue.  Please feel free to add additional context to 732.  You're correct about the main focus of 732.  If you think that having the backleveled ruby-nats is in and of itself an issue, let's close this issue and create a new one just for that.  I will say that the tentative plan is to remove NATS entirely from the CC within the next "few" months, once we no longer have to support the DEAs.  But I don't think there's a firm timeline for that.  Once that happens, then obviously a lot of pain will disappear as well.

**Closed** 2017-03-27 20:55 UTC
Labels: unscheduled
