### ISSUE TITLE
improvement for api endpoint:"Retrieve a Particular Service Instance" 

### ISSUE THREAD

**Issue by mcelep** [cloudfoundry/cloud_controller_ng#680] opened 2016-09-16 14:57 UTC
## Issue

The API endpoint for "Retrieve a Particular Service Instance" does not provide the 'parameters' object that can be optionally provided during  [service provisioning](https://docs.cloudfoundry.org/services/api.html#provisioning).

## Context
Asynchronous service provisioning requests might take days to complete in cases where manual human interaction (due to IT governance processes) is required. In such cases, the original requestor might not even remember the content of the 'parameters' object that she used in the initial request. That would mean she has no way to see how she meant to configure this service until the provisioning is completed. Even when a service provisioning is completed, the service broker would then somehow need to indicate what kind of 'parameters' (configuration) are applied for a given service instance. It is better to keep this piece information on cloud controller rather than relying on service provider.

## Possible Fix
The API endpoint for "Retrieve a Particular Service Instance" should provide the 'parameters' object in its response if such an object is provided with the initial service provisioning request.

**Comment by SocalNick** [comment] 2016-09-20 19:15
@mcelep the parameters for a service instance are intended to pass-through the Cloud Controller and are only of use to the Service Broker. One option for relaying the configuration would be displaying it on a Service Dashboard. The broker can respond to the Cloud Controller's provision request with a `dashboard_url` where a user can go to see the status.

cc @avade @shalako

**Comment by shalako** [comment] 2016-09-20 19:23
Two additional solutions:
- `GET /v2/service_instances/:guid` to CC could trigger a call to a new broker API endpoint `GET /v2/service_instances/:guid` on the broker, which could return these parameters
- CC could persist the requested parameters as an opaque object with the service instance and return the params with the GET

**Comment by avade** [comment] 2016-09-21 13:44
> CC could persist the requested parameters as an opaque object with the service instance and return the params with the GET

+1 for this solution. It means the service broker can simply provision rather than storing the state of what was asked for.

**Comment by mcelep** [comment] 2016-09-29 08:25
Relying on the service provider's dashboard does not cover all the cases, as some services come without a dashboard.
The 1st solution offered by @shalako i.e. relying on the service broker for providing the arbitrary parameter sounds good.

**Comment by SocalNick** [comment] 2016-10-06 22:20
@shalako @avade do you have a list of feature requests for the Service Broker API that we can add this to? It's not really an "issue" for Cloud Controller. I'd like to close this issue but not lose the feature request.

**Comment by mcelep** [comment] 2016-10-11 07:01
@SocalNick, Cloud Controller would still need to be updated so that when this [endpoint](https://apidocs.cloudfoundry.org/244/service_instances/retrieve_a_particular_service_instance.html) is called, it can call Service Broker endpoint(`GET /v2/service_instances/:guid`) and use the data 'arbitrary/custom parameters'.

**Comment by SocalNick** [comment] 2016-10-11 14:56
@mcelep absolutely, it's just not a bug and not a top priority feature for the CAPI team. @shalako and @avade are driving Services on Cloud Foundry more holistically than I can at this point in time.

**Comment by shalako** [comment] 2016-10-11 17:37
@SocalNick Sent you an email about where to capture this request.

**Comment by SocalNick** [comment] 2016-10-14 17:17
@mcelep I've recorded this in our list of requests. thanks for the suggestion!

**Closed by SocalNick** 2016-10-14 17:17 UTC
Labels: unscheduled
