### ISSUE TITLE
Admins Cannot see space scoped service brokers

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cloud_controller_ng#1065] opened 2018-01-22 18:23 UTC
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When trying `cf marketplace`, `cf create-service` or other activities involing space-scoped service brokers/plans, if a user has `cloud_controller.admin`, but is not a space-developer of the space, they cannot see the space-scoped service plans.

## Context

Space developers can see and use the space-scoped services, but admins cannot. This may lead to confusion and difficulty troubleshooting issues for users. Resolving this would currently require admins to be added as space-developers everywhere which can cause flags to be raised when auditing who has access to what org/space (e.g. "Why is a user not on the team is a space developer?").

## Steps to Reproduce

1. Create a space-scoped service somewhere.
2. Log in as a user with cloud_controller.admin, and try to create a service in the above space.
3. After that fails, add the user as a space developer, and then create the service-broker 

## Expected result

Step two should have succeeded, obviating the need for step 3.

## Current result

Step 2 fails, and step 3 succeeds

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by lisamcho** [comment] 2018-03-07 00:25
Hi @geofffranks, 

Thanks for reporting this issue.
Could you provide more details on the steps you ran, along with the version of cloud_controller?
What is the error that you are seeing when you attempt to create the service as an admin?
We weren't able to reproduce this issue with the following steps:

```
cf auth test test # A space developer
cf target -o org -s space
ruby setup_new_broker.rb  space-broker <url>
# The ruby script essentially pushes and app as a broker and does this:
# cf create-service-broker space-broker user password space-broker.capi.land —space-scoped
cf auth admin <password>
cf target -o org -s space
cf marketplace -v
# We confirmed here that the service broker includes space_guid of the space that it is scoped to.

cf create-service fake-service-405c7d47-5dd6-4e71-ac87-0cb551c8308d fake-plan si
Creating service instance si in org org / space space as admin...
OK
```

In this case, the admin user was able to create a service-instance off a space-scoped service.
We also tried reproducing with a different user that only has cloud_controller.admin.
```
cf create-user test test
uaac member add cloud_controller.admin test
```
-Lisa and @ericpromislow

**Comment by zrob** [comment] 2018-03-28 21:08
We have been unable to reproduce this and believe it is a dupe of https://github.com/cloudfoundry/cloud_controller_ng/issues/827, which has been resolved.

If you are able to provide steps that reproduce this issue on latest capi-release please open a new issue.

**Closed by zrob** 2018-03-28 21:08 UTC
Labels: delivered

**Comment by geofffranks** [comment] 2018-03-29 20:30
Thanks, yeah this looks like it is now resolved for us as well
