### ISSUE TITLE
The CC worker process fails to drain if the DB is not available

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cloud_controller_ng#973] opened 2017-11-01 23:56 UTC
## Issue

If the CCDB is not available, the CC worker processes (both local and external), can error out trying to run their drain scripts. This may soon become more common as CF users start using smaller footprint CF installations that do not have HA DB or DNS.

## Steps to Reproduce

I _think_ these are the steps, but I may be messing up the order slightly

- Deploy CF with a single DB node
- `monit stop` DB processes
- Attempt to recreate a worker or API VM
- Verify that recreate fails due to drain script erroring

## Expected result

Drain succeeds even if DB is gone.

## Current result

Drain errors as described above.

## Possible Fix

Up for suggestions, first thing that comes to mind is letting the worker drain gracefully for a bit then kill the worker process before BOSH decides the drain has timed out.

**Comment by ljfranklin** [comment] 2017-11-01 23:58
Here's example output from BOSH:

```
02:30:34
Task 95 | 09:29:44 | Preparing deployment: Preparing deployment (00:00:16)
02:30:34
Task 95 | 09:30:15 | Preparing package compilation: Finding packages to compile (00:00:01)
02:30:34
Task 95 | 09:30:16 | Compiling packages: golang-1.8-linux/1509998fbf5c66cb8fc361a479beafb41ef8cc14 (00:01:36)
02:32:01
Task 95 | 09:31:52 | Compiling packages: bosh-dns/ea00a47a01fc814ecf2f0399017d9dcc6e0b1a44 (00:00:20)
02:33:00
Task 95 | 09:32:48 | Updating instance database: database/1f1c32b6-7604-4e76-8b1f-2515c25fd11c (0) (canary) (00:04:04)
02:36:55
Task 95 | 09:36:52 | Updating instance control: control/d00a5854-0258-439c-8f2b-342169f2e8d5 (0) (canary) (00:01:01)
02:38:09
                   L Error: Action Failed get_task: Task 51426ba8-9936-4478-5185-9630efe977b4 result: 1 of 8 drain scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: consul_agent, cloud_controller_clock, bbs, auctioneer, cloud_controller_worker, adapter, reverse_log_proxy.
02:38:09
Task 95 | 09:37:53 | Error: Action Failed get_task: Task 51426ba8-9936-4478-5185-9630efe977b4 result: 1 of 8 drain scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: consul_agent, cloud_controller_clock, bbs, auctioneer, cloud_controller_worker, adapter, reverse_log_proxy.
02:38:09

02:38:09
Task 95 Started  Wed Nov  1 09:29:44 UTC 2017
02:38:09
Task 95 Finished Wed Nov  1 09:37:53 UTC 2017
02:38:09
Task 95 Duration 00:08:09
02:38:09
Task 95 error
02:38:09
```

**Comment by ljfranklin** [comment] 2017-11-02 00:03
Looks like we tried to add a "wait then kill" here: https://github.com/cloudfoundry/cloud_controller_ng/commit/ab9a1de5447ac350d45d035ad8b4f4f798f927a3. But since we are killing the local workers [serially](https://github.com/cloudfoundry/capi-release/blob/bf7a47e0e3ee29179709d7d4019306c4b317084c/jobs/cloud_controller_ng/templates/drain.sh.erb#L23-L33) we may still be hitting a drain timeout, not sure.

**Comment by elenasharma** [comment] 2017-11-13 19:26
@ljfranklin When we tried to follow your steps for reproduction, we noticed that the worker never went down after stopping all of the database processes. Aside from that, we couldn't reproduce the issue.

Here are the steps we took:

1. deploy CF with a single DB
1. monit stop all processes on DB VM
1. ran `bosh recreate api`
1. recreate completed successfully

**Comment by ljfranklin** [comment] 2017-11-14 18:17
@elenasharma I wonder if setting `cc.jobs.local.number_of_workers` on the API VM to a number higher than the default of `2` would make this easier to reproduce. From the bosh logs above, bosh failed with a drain timeout after 1 minute. If we allow the workers a max of 30 seconds to drain, two workers might drain in time but sometimes they might not.

**Comment by rainmaker** [comment] 2017-11-20 22:45
We've tried to reproduce this again with an increased number of local workers. So far, we're unable to see the same type of failure, because CC and its workers start failing as soon as the database goes away. When we go to stop that VM, bosh decides to focus on restarting the `diego-api` VM, which is also failing due to the lack of database. As a result, we haven't been able to see the drain scripts run yet.

**Comment by ljfranklin** [comment] 2017-11-21 18:44
Copy pasting my message from slack:

It may have been on a delete deployment, does BOSH stop all VMs in parallel in that case?

In practice this may be hard to reproduce. In theory our drain script seems flawed as we drain each local worker serially and each worker can take up to 30 seconds. In the logs in the issue, BOSH failed with a drain timeout after 1 minute. So with two or more workers it seems theoretically possible to hit the drain timeout but I'm not sure how to get the workers to hit their 30 second "kill and wait" limit.

**Comment by maryamklabib** [comment] 2017-12-04 23:01
Hi @ljfranklin,

We're a bit confused. From what we understand, this is theoretically a possible race condition, but the part we don't understand is when this situation would happen in practice. Can you think of an example of when ccdb would be gone and the drain scripts not run yet? We talked to @rainmaker and she said they tested this using 4 local workers last time.

It's our understanding that theoretically we _might_ be able to replicate the 30 second "kill and wait" time by keeping multiple workers busy (uploading blobs, etc.), but we can't think of a way to stop cc and its workers from crashing once the db is gone.

What are your thoughts? Have you been able to reproduce this issue again?

CAPI Team Pair (Maryam and @anniesing)

**Comment by ljfranklin** [comment] 2017-12-05 15:43
@maryamklabib From @rainmaker's last message "bosh decides to focus on restarting the diego-api VM", the logs higher up look like the small footprint PCF install so the co-location strategy might be why the user saw the error. All the API jobs like CC and Diego API are all on the same VM, not sure whether BOSH stops them in parallel in that case or not.

While I appreciate the focus on creating a reproducible test case, reproducing race conditions is hard. I'll leave it up to y'all whether to:

- Keep trying to reproduce or
- Go ahead anyway and update scripts to stop local workers in parallel or
- Close this as can't reproduce and see if it comes up again

**Comment by anniesing** [comment] 2017-12-05 21:53
We tried again to reproduce this. We're not sure where the 1 minute timeout you were seeing is coming from since it looks like [bosh drain scripts do not have timeouts](https://bosh.io/docs/job-lifecycle.html#stop). It's possible that you had two local workers, so the 1 minute comes from the two 30-second timeouts for each local worker.

We tried to reproduce this more directly by adding network rules to prevent the workers from reaching the database: `iptables -A INPUT -s <db ip> -j DROP`. Interestingly, it looks like workers can operate and drain without database access (they just continuously log errors). With this rule in place, we were able to manually run the drain script, re-create the instance, and even delete the deployment. 

Unfortunately, we haven't been able to reproduce this issue using the information available. We are going to close this issue for now. If you, or anyone else, sees this again, we will be happy to re-visit it. If someone does see this, getting logs from the worker process that failed to drain will make diagnosing this issue much easier.

Thanks,
Annie and @Gerg

**Closed** 2017-12-05 21:54 UTC
Labels: in progress
