### ISSUE TITLE
Jar with Zip64 encoding fails to be deployed.

### ISSUE THREAD

**Issue by Yogeshberia** [cloudfoundry/cloud_controller_ng#1607] opened 2020-05-11 03:24 UTC
[OPERATION (1).log](https://github.com/cloudfoundry/cloud_controller_ng/files/4607414/OPERATION.1.log)
[OPERATION.log](https://github.com/cloudfoundry/cloud_controller_ng/files/4607415/OPERATION.log)

Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
Related Issue: https://github.com/cloudfoundry/cf-java-client/issues/877
Jar with zip64 archive encoding fails to be deployed.
Error is: Description: The app upload is invalid: Invalid zip archive.#

## Context
Some of our projects are large in size and written in scala.
Because this has more than 65535 entries, we are forced to use the zip64 encoding for the projects.
However, deployment to cloud foundry fails for such jar files with the above mentioned errors.
'cf push' however works but not cf-deploy/cf-bg-deploy.

## Steps to Reproduce
- Create a simple application packaged as jar.
- Jar encoding is zip64 instead of zip. [Can be done in various ways depending on OS/Libs used.]
- Try to upload to a CF system using cf-deploy.

## Expected result
Upload & Deployment succeeds as normal zip archives do.

## Current result
Error is: Description: The app upload is invalid: Invalid zip archive.#

[include relevant logs]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by radoslav-d** [comment] 2020-05-11 09:36
I am from the Deploy service team and I want to add more context to this issue. We have done an investigation and we can confirm that the problem comes from the CC. We use the CF Java client to upload the binaries of apps, which we treat like blobs.
The error message `Invalid zip archive.` comes when polling the CC for upload status.
The reason why `cf push` works is that the _cf cli push command_ does a further handling of archives on the client side (with Golang lib), but the CF Java client upload functionality does not (and I think it should not). The related github issue may add more clarity -> https://github.com/cloudfoundry/cf-java-client/issues/877

**Comment by Gerg** [comment] 2020-08-07 22:26
@Yogeshberia @radoslav-d I attempted to reproduce this issue, but didn't see the behavior you described:

First, I created a zip64 file:
```
zip -fz ./zip.zip .**/*
```
Proof that it's zip64:
```
zipdetails zip.zip
...
000003D Extra ID #0003        0001 'ZIP64'
```
I created a new package:
```
cf curl -X POST /v3/packages -d '{"type": "bits", "relationships": {"app": {"data": {"guid": "92b9e25b-7d9f-4f67-997b-19f9c9349b7d"}}}}'
{
  "guid": "6d03ce40-f50d-4b63-8300-e3f790eaefdb",
  "created_at": "2020-08-07T21:31:01Z",
  "updated_at": "2020-08-07T21:31:01Z",
  "type": "bits",
  "data": {
    "error": null,
    "checksum": {
      "type": "sha256",
      "value": null
    }
  },
  "state": "AWAITING_UPLOAD",
  "relationships": {
    "app": {
      "data": {
        "guid": "92b9e25b-7d9f-4f67-997b-19f9c9349b7d"
      }
    }
  },
  "metadata": {
    "labels": {

    },
    "annotations": {

    }
  },
  "links": {
    "self": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb"
    },
    "upload": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb/upload",
      "method": "POST"
    },
    "download": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb/download"
    },
    "app": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/apps/92b9e25b-7d9f-4f67-997b-19f9c9349b7d"
    }
  }
}
```
And uploaded the zip64 file:
```
curl -H "Authorization: $(cf oauth-token)" -H "Content-Type: multipart/form-data" api.butter-koala.lite.cli.fun/v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb/upload -F bits=@"zip.zip" -v
...
```
And the package processed successfully:
```
cf curl /v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb
{
  "guid": "6d03ce40-f50d-4b63-8300-e3f790eaefdb",
  "created_at": "2020-08-07T21:31:01Z",
  "updated_at": "2020-08-07T21:35:36Z",
  "type": "bits",
  "data": {
    "error": null,
    "checksum": {
      "type": "sha256",
      "value": "6c7d82f692282ea27332c0284c78a533e57a79289b367227e4923f63787a4389"
    }
  },
  "state": "READY",
  "relationships": {
    "app": {
      "data": {
        "guid": "92b9e25b-7d9f-4f67-997b-19f9c9349b7d"
      }
    }
  },
  "metadata": {
    "labels": {

    },
    "annotations": {

    }
  },
  "links": {
    "self": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb"
    },
    "upload": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb/upload",
      "method": "POST"
    },
    "download": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/packages/6d03ce40-f50d-4b63-8300-e3f790eaefdb/download"
    },
    "app": {
      "href": "https://api.butter-koala.lite.cli.fun/v3/apps/92b9e25b-7d9f-4f67-997b-19f9c9349b7d"
    }
  }
}
```

The zip64 format may be a distraction from the underlying issue here. Do you see anything in the Cloud Controller logs with more details about the failure? For example this line:
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/app_packager.rb#L25

Thanks,
Greg

**Comment by radoslav-d** [comment] 2020-09-18 12:36
Hello @Gerg @Yogeshberia ,
As I see you are using the V3 endpoints and as I remember the issue cannot be reproduced using them, but only V2 endpoints. However, we are still orchestrating V2 endpoint calls in the MTA Deployment service backend. We are planning a migration to V3 in the near future (no concrete dates yet).
I will send a link to the backlog item in our JIRA to @Yogeshberia which can be used to track the progress of the migration from V2 to V3 endpoints.
Best regards,
Rado

**Comment by Gerg** [comment] 2020-09-18 22:21
In that case, It sounds like upgrading to v3 is probably the best path forward. I'm going to close this issue since it appears fixed in the latest API version. Feel free to re-open if you continue to have issues after upgrading to v3.

**Closed by Gerg** 2020-09-18 22:21 UTC
Labels: PM Review, unscheduled
