### ISSUE TITLE
500 Internal Server Error when querying for all spaces

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cloud_controller_ng#717] opened 2016-11-15 12:42 UTC
## Issue

Call to ```/v2/spaces?inline-relations-depth=1``` returns an "500 Internal Server Error".

## Context

From time to time querying for all spaces (i.e. ```/v2/spaces?inline-relations-depth=1```) results in an error. In the log of the Cloud Controller, we see the following message:

```
<11>2016-11-15T08:42:10.803786+00:00 10.0.65.66 vcap.cloud_controller_ng [job=api_z1 index=0]  {"timestamp":1479199330.8037431,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"undefined method `name' for nil:NilClass\", \"error_code\"=>\"CF-NoMethodError\", \"backtrace\"=>[\"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/models/runtime/app.rb:408:in `name'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/app_presenter.rb:11:in `entity_hash'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/base_presenter.rb:8:in `to_hash'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:80:in `block in serialize_to_many_relationship'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:73:in `map'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:73:in `serialize_to_many_relationship'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:52:in `block in serialize_relationships'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:39:in `each'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:39:in `serialize_relationships'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:26:in `block in to_hash'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:16:in `tap'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/relations_presenter.rb:16:in `to_hash'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/space_presenter.rb:20:in `entity_hash'\", \"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-d3426de014501667f67c2d3690a5821895a1e537/cloud_controller_ng/app/presenters/v2/base_presenter.rb:8:in `to_hash'\", \"/var/vcap/data/packages/cloud_controll...","log_level":"error","source":"cc.api","data":{"request_guid":"ea0e059d-e820-4b20-583e-d71f91cfac1e::bf1facba-6cc1-4953-b954-86cc68e4b652"},"thread_id":47062533833460,"fiber_id":47062534857620,"process_id":5577,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb","lineno":53,"method":"block in registered"}
```

The last thing that happened before the error was ```SELECT * FROM "apps" WHERE ("apps"."guid" = 'ffafef8d-5508-41e1-b41a-5df7476c1301') LIMIT 1```. When I (at a later point in time) tried to query for this app, it did not exist anymore.

As the request to ```/v2/spaces?inline-relations-depth=1``` returns a lot of data and takes about 7 seconds on our CF system, I am wondering if the error could have been caused by the fact that the app was deleted *while the other request was still running*. At least the stacktrace contains ```models/runtime/app``` and the error is ```undefined method `name' for nil:NilClass```.

**Comment by achawki** [comment] 2017-01-23 16:49
We also see this problem with `cf apps` and `cf services`. It has the same root cause.
It's reproducible:
* Create multiple apps
* Delete them all
* Invoke throughout `cf services`

**Comment by thausler786** [comment] 2017-01-26 00:40
@philippthun,

We tried to reproduce your error using the same `/v2/spaces?inline-relations-depth=1` and doing a simultaneous `cf delete app foo` on an app under one of the spaces.  It performed as expected for us (cf on bosh-lite with ~1000 apps), and we couldn't get a 500 out of it.

We also didn't see the DB query you mentioned in our output when only running `/v2/spaces?inline-relations-depth=1`, so we think it is likely that that query came from another user on your system, maybe the one who deleted that app?

@achawki, do you have more details on how to reproduce this error?  Perhaps a script? We aren't sure what you mean by "Invoke throughout `cf services`"

We'll add details from our investigation [here](https://www.pivotaltracker.com/story/show/134347817).

Best,
@thausler786 && @ljfranklin

**Comment by achawki** [comment] 2017-01-26 08:29
@thausler786,

We used following scripts:

Setup:
```
#!/bin/bash

for i in `seq 1 50`; do
   cf push hello-node-$i --random-route
done
```

Deletion of apps:
```
#!/bin/bash

for i in `seq 1 50`; do
   cf delete hello-node-$i  -f -r
done
```

Invoke throughout `cf services`:
```
#!/bin/bash

for i in `seq 1 1000`; do # Can be any high number, should run until the deletion is finished
   cf services >services-$i.log
done
```

At least in some log files we see the 500 Internal Server Error

**Comment by michaelxupiv** [comment] 2017-01-27 20:04
Hey @philippthun & @achawki ,

Thanks for submitting this issue. We added this [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/ff46f2ce26092e57cad13336874ebb40192023f3) to exclude concurrently deleted apps from our summaries controller. We ran your scripts again and we didn't see the issue come up anymore. Please let us know if you still have any concerns, closing this issue for now.

Thanks,
CAPI Pair - @ericpromislow && @michaelxupiv

**Closed by michaelxupiv** 2017-01-27 20:04 UTC
Labels: in progress
