### ISSUE TITLE
v2 api "greater_than" filter doesn't work as expected

### ISSUE THREAD

**Issue by jiahaoliang** [cloudfoundry/cloud_controller_ng#806] opened 2017-04-14 23:53 UTC
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

 I am playing around with the v2 api with timestamp. When I query for result “greater than” SOME_TIMESTAMP, the api returns results including the event happened right at that  SOME_TIMESTAMP.

## Context

Bosh-lite setup

#bosh deployments
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'

+-----------------+----------------------------+-----------------------------------------------------+--------------+
| Name            | Release(s)                 | Stemcell(s)                                         | Cloud Config |
+-----------------+----------------------------+-----------------------------------------------------+--------------+
| cf-warden       | cf/253                     | bosh-warden-boshlite-ubuntu-trusty-go_agent/3363.12 | none         |
+-----------------+----------------------------+-----------------------------------------------------+--------------+
| cf-warden-diego | cf-networking/0.18.0+dev.3 | bosh-warden-boshlite-ubuntu-trusty-go_agent/3363.12 | none         |
|                 | cf/253                     |                                                     |              |
|                 | cflinuxfs2-rootfs/1.57.0   |                                                     |              |
|                 | diego/1.10.1               |                                                     |              |
|                 | garden-runc/1.3.0          |                                                     |              |
+-----------------+----------------------------+-----------------------------------------------------+--------------+

Deployments total: 2

## Steps to Reproduce

#cf curl "/v2/events?q=type:audit.space.create&q=timestamp>'2017-04-05T23:37:15Z'" | python -m json.tool

I also tried replace '>' with '%3E' but got the same result.

## Expected result

"resources" should be an empty list in my case.

## Current result

{
    "next_url": null,
    "prev_url": null,
    "resources": [
        {
            "entity": {
                "actee": "7d0471c8-092d-4c41-9ff6-ed614058db2e",
                "actee_name": "tryout",
                "actee_type": "space",
                "actor": "be58c9e6-8b55-4bba-aa9f-3bf8a31cf5ba",
                "actor_name": "admin",
                "actor_type": "user",
                "actor_username": "admin",
                "metadata": {
                    "request": {
                        "allow_ssh": true,
                        "name": "tryout",
                        "organization_guid": "829e1861-344e-4bd6-b14b-14f37bc8aa16"
                    }
                },
                "organization_guid": "829e1861-344e-4bd6-b14b-14f37bc8aa16",
                "space_guid": "7d0471c8-092d-4c41-9ff6-ed614058db2e",
                "timestamp": "2017-04-05T23:37:15Z",
                "type": "audit.space.create"
            },
            "metadata": {
                "created_at": "2017-04-05T23:37:15Z",
                "guid": "7c44934c-dcd5-4ba5-b92f-6fb55323d4a5",
                "updated_at": "2017-04-05T23:37:15Z",
                "url": "/v2/events/7c44934c-dcd5-4ba5-b92f-6fb55323d4a5"
            }
        }
    ],
    "total_pages": 1,
    "total_results": 1
}

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by nicregez** [comment] 2017-04-18 17:58
@jiahaoliang,

Thanks for opening this issue. We analyzed how we are filtering our dataset based on the timestamp query parameter. Turns out, Postgres stores fractional seconds in the database, but we display timestamps only on the second precision. You can check the values of the timestamp column in your database record, and it will contain fractional seconds, and therefore, it will be selected by the ">".

Closing this issue as it is not a bug. Let us know if you have any other concerns.
Side comment: MySql does not store fractional seconds. This seems like just a behavior in Postgres.

Thanks,
CAPI Community Pair - @nicregez && @michaelxupiv

**Closed by nicregez** 2017-04-18 17:58 UTC
Labels: in progress
