### ISSUE TITLE
Check a HTTP Route exists returns incorrect response for route without path when route with path exists

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/cloud_controller_ng#1274] opened 2018-12-19 19:52 UTC
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

In https://github.com/cloudfoundry/cli/issues/1406, submitter reports the following unexpected behavior, which I have reproduced:

```
$ cf create-route test istio-acceptance.routing.cf-app.com -n scoen-tmp --path /foo
Creating route scoen-tmp.istio-acceptance.routing.cf-app.com/foo for org scoen / space test as admin...
Route scoen-tmp.istio-acceptance.routing.cf-app.com/foo has been created.
OK

$ cf create-route test istio-acceptance.routing.cf-app.com -n scoen-tmp 
The app cannot be mapped to route scoen-tmp.istio-acceptance.routing.cf-app.com because the route exists in a different space.
FAILED
```

This workflow should be supported.

## Context

`GET /v2/routes/reserved/domain/:domain_guid/host/:host?path=:path` appears to be returning an incorrect response `204` for a route without a path does not exist, when a route with the same domain and host, as well as a path, does exist.

## Steps to Reproduce

See above

## Expected result

According to the [API docs](https://apidocs.cloudfoundry.org/6.7.0/routes/check_a_http_route_exists.html), I would expect the API to return a `404` and the CLI to consequently return a success.

## Current result

API returns a 204 and CLI consequently returns an error

**Comment by cwlbraa** [comment] 2019-01-04 19:59
In your original trace from the previous issue, the CLI sends the following:
`GET /v2/routes/reserved/domain/:domain_guid/host/:host`
```
REQUEST: [2018-12-19T11:35:29-08:00]
GET /v2/routes/reserved/domain/57c74a0d-b146-4f8b-8712-636f4e92ca6c?host=scoen-tmp HTTP/1.1
Host: api.istio-acceptance.routing.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-12-19T11:35:29-08:00]
HTTP/1.1 204 No Content
Alt-Svc: clear
Date: Wed, 19 Dec 2018 19:35:29 GMT
Server: nginx
Via: 1.1 google
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: f13983af-20f0-415c-6f32-08e228230b2b::ec68b858-f561-4940-83d2-12a8ae370ff8
{}
```
But here you report that the behavior is incorrect for 
`GET /v2/routes/reserved/domain/:domain_guid/host/:host?path=:path`

That means the absence of a path should indicate that we're checking for the existence of the route for `/`, right?

**Comment by textbook** [comment] 2019-07-11 09:41
I just ran across this when changing the CF deployment for [pivotal/postfacto](https://github.com/pivotal/postfacto), trying to remove any CORS issues by doing e.g.:

  - `my-cool-retro-app.cfapps.io` <- NGINX serving the client React app
  - `my-cool-retro-app.cfapps.io/api` <- Ruby buildpack running the Rails server

As it stands this bug means you **must** deploy the client first, otherwise when you deploy the server you see _"the route exists in a different space"_ (which is partly confusing because the conflicting route is *not* necessarily in a different space - this isn't a great error!)

If there's no way to explicitly set an empty/`/` path, then I'd say that: yes, the absence of the `path` query parameter should imply that we're checking for the route _without_ a path, and that the same route _with_ a path should not be counted as a conflict.

**Comment by shinmyung0** [comment] 2019-08-16 21:45
This is also a serious issue for us. We are migrating our main homepage along with some other UI pages to PCF which are maintained by different teams working at different paces. 

Because there are some existing frontend UIs that have already migrated (for example `/foo` path), we are running into trouble migrating our homepage (`/` path). This complicates things greatly since some UI pages are already taking production traffic....

**Comment by David-Pivotal** [comment] 2019-08-26 08:20
A head up that one of the customers hit this issue too. This brings lots of extra trouble to create the "/" route. Could you help prioritize this issue?

**Comment by David-Pivotal** [comment] 2019-08-26 08:22
I figure out another way to create the "/" route.

1.) This issue can be reproduced.
```
jump-user@linux-jump-box-1804:~$ cf create-route system cfapps-03.haas-59.pez.pivotal.io -n scoen-tmp --path /foo
Creating route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io/foo for org system / space system as admin...
Route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io/foo has been created.
OK
 
jump-user@linux-jump-box-1804:~$ cf create-route system cfapps-03.haas-59.pez.pivotal.io -n scoen-tmp
Creating route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io for org system / space system as admin...
The app cannot be mapped to route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io because the route exists in a different space.
FAILED
```

2.) It reports the route exist but not in fact, scoen-tmp.cfapps-03.haas-59.pez.pivotal.io
```
jump-user@linux-jump-box-1804:~$ cf check-route scoen-tmp cfapps-03.haas-59.pez.pivotal.io
Checking for route...
OK
Route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io does exist
```
3.) Let's map it directly to one dummy app which will create it automatically.
```
jump-user@linux-jump-box-1804:~$ cf map-route hello-php cfapps-03.haas-59.pez.pivotal.io -n scoen-tmp
Creating route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io for org system / space system as admin...
OK
Adding route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io to app hello-php in org system / space system as admin...
OK
```
4.) Then release it from the dummy app and this route is available for use now.
```
jump-user@linux-jump-box-1804:~$ cf unmap-route hello-php cfapps-03.haas-59.pez.pivotal.io -n scoen-tmp
Removing route scoen-tmp.cfapps-03.haas-59.pez.pivotal.io from app hello-php in org system / space system as admin...
OK
jump-user@linux-jump-box-1804:~$ cf routes|egrep "scoen-tmp|space host"
space host domain port path type apps service
system scoen-tmp cfapps-03.haas-59.pez.pivotal.io /foo
system scoen-tmp cfapps-03.haas-59.pez.pivotal.io
```

**Comment by abbyachau** [comment] 2019-09-19 20:46
@shalako this appears to have been fixed on v3/v7

```
$ ./cf7 create-route issue.example.com -n abby --path /new_page
Creating route abby.issue.example.com/new_page for org abby / space dodo as admin...
Route abby.issue.example.com/new_page has been created.
OK


$ ./cf7 create-route issue.example.com -n abby
Creating route abby.issue.example.com for org abby / space dodo as admin...
Route abby.issue.example.com has been created.
OK
```

**Comment by cwlbraa** [comment] 2020-01-23 00:44
with hesitation I'm going to close this as fixed in v3+v7

**Closed by cwlbraa** 2020-01-23 00:44 UTC
Labels: bug, unscheduled, v2-only
