### ISSUE TITLE
Received Unknown Error

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cloud_controller_ng#1709] opened 2020-06-29 23:33 UTC
I received an Unknown Error when pushing a golang application on cf-for-k8s.  
The app is the golang included in CATs, the asset path is included in the below terminal output.  
Terminal output includes API and CLI versions, as well as the manifest used.  
I'm pretty sure this is an invalid manifest issue, since that's what I am tinkering with. 
I'll share what the manifest issue was in a follow on comment.    
I would expect to get a more descriptive error.

cf-for-k8s version:
```
± zr |master {1} ?:7 ✗| → git lg
* 9854f5b - (HEAD -> master, origin/master, origin/develop, origin/HEAD) Bump capi-k8s-release to 5fb4c89475b347fce449068e9f260732a0e43d74 (3 days ago) relint-ci & relint-ci
```

failed push and details
```
± zr |master U:1 ?:1 ✗| → cf p a
Pushing app a to org test / space test as admin...
Applying manifest file /Users/pivotal/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/golang/manifest.yml...
Manifest applied
Packaging files to upload...
Uploading files...
 584 B / 584 B [============================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Loading secret for "gcr.io" from secret "cc-kpack-registry-auth-secret-ver-1" at location "/var/build-secrets/cc-kpack-registry-auth-secret-ver-1"
   Successfully downloaded cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000/cc-packages/3a/4f/3a4f57df-9105-49c5-b79c-3f58a173d45d in path "/workspace"
   paketo-buildpacks/go-compiler 0.0.160
   paketo-buildpacks/go-mod      0.0.128
   Restoring metadata for "paketo-buildpacks/go-mod:app-binary" from app image
   Go Compiler Buildpack 0.0.160
   Resolving Go version
   Candidate version sources (in priority order):
   <unknown> -> ""

   Selected Go version (using <unknown>): 1.13.12

   Executing build process
   Installing Go 1.13.12
   Completed in 16.544s

   Go Mod Buildpack 0.0.128
   Setting environment variables
   : Contributing to layer
   main
   : Contributing to layer
   Running `go install`
   : Contributing to layer
   Contributing start command
   Process types:
   web: /layers/paketo-buildpacks_go-mod/app-binary/bin/main
   Reusing layers from image 'gcr.io/cf-capi/cf-workloads/ac2eb6de-a036-4498-be33-6f96cad5a029@sha256:2e493f5c52f3e527cb08979ea86efaa4a7ff454a919a3b001b4f7a9be95a892c'
   Reusing layer 'launcher'
   Reusing layer 'paketo-buildpacks/go-mod:app-binary'
   Reusing 1/1 app layer(s)
   Reusing layer 'config'
   *** Images (sha256:2e493f5c52f3e527cb08979ea86efaa4a7ff454a919a3b001b4f7a9be95a892c):
   gcr.io/cf-capi/cf-workloads/ac2eb6de-a036-4498-be33-6f96cad5a029
   gcr.io/cf-capi/cf-workloads/ac2eb6de-a036-4498-be33-6f96cad5a029:b3.20200629.232151
   Adding cache layer 'paketo-buildpacks/go-compiler:go'
   Adding cache layer 'paketo-buildpacks/go-mod:go-cache'
   Adding cache layer 'paketo-buildpacks/go-mod:go-mod'
   Build successful

Waiting for app a to start...

Unexpected Response
Response Code: 500
Request ID:    ed5e57ff-d86a-435e-9d60-4c2b22bf0335::5ebad8b8-6b08-4526-bb59-559d4cd017ae
Code: 0, Title: , Detail: {
  "errors": [
    {
      "title": "UnknownError",
      "detail": "An unknown error occurred.",
      "code": 10001
    }
  ]
}
FAILED

 2020-06-29 16:22:47 ⛅️  ruby 2.5.5p157 wlan-10-81-130-143 in ~/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/golang
± zr |master U:1 ?:1 ✗| → cf curl /
{
   "links": {
      "self": {
         "href": "https://api.cf.example.com"
      },
      "bits_service": null,
      "cloud_controller_v2": {
         "href": "https://api.cf.example.com/v2",
         "meta": {
            "version": "2.151.0"
         }
      },
      "cloud_controller_v3": {
         "href": "https://api.cf.example.com/v3",
         "meta": {
            "version": "3.86.0"
         }
      },
      "network_policy_v0": {
         "href": "https://api.cf.example.com/networking/v0/external"
      },
      "network_policy_v1": {
         "href": "https://api.cf.example.com/networking/v1/external"
      },
      "login": {
         "href": "https://login.cf.example.com"
      },
      "uaa": {
         "href": "https://uaa.cf.example.com"
      },
      "credhub": null,
      "routing": {
         "href": "https://api.cf.example.com/routing"
      },
      "logging": {
         "href": "wss://doppler.cf.example.com:443"
      },
      "log_cache": {
         "href": "https://log-cache.cf.example.com"
      },
      "log_stream": {
         "href": "https://log-stream.cf.example.com"
      },
      "app_ssh": {
         "href": "TODO.TODO",
         "meta": {
            "host_key_fingerprint": "placeholder",
            "oauth_client": "placeholder"
         }
      }
   }
}

 2020-06-29 16:26:54 ⛅️  ruby 2.5.5p157 wlan-10-81-130-143 in ~/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/golang
± zr |master U:1 ?:1 ✗| → cf -v
cf version 7.0.0+b67291ee4.2020-06-17

 2020-06-29 16:26:56 ⛅️  ruby 2.5.5p157 wlan-10-81-130-143 in ~/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/golang
± zr |master U:1 ?:1 ✗| → cat manifest.yml
---
applications:
- env:
    GOPACKAGENAME: go-online
  processes:
  - type: web
    command: /layers/paketo-buildpacks_go-mod/app-binary/bin/main
  - type: worker
    command: sleep 1000
    instances: 1
```

**Comment by selzoc** [comment] 2020-07-07 18:43
@zrob do you have the associated ccng logs for that request?  That would help us narrow down what's happening here.

**Comment by zrob** [comment] 2020-07-12 00:02
I do not. Was hoping it could be repro'd using the same app and manifest.

**Comment by cwlbraa** [comment] 2020-09-08 22:13
is it possible that 

```
  processes:
  - type: web
    command: /layers/paketo-buildpacks_go-mod/app-binary/bin/main
```

causes the issue? are custom commands working today in the CNB push flow?

**Comment by matt-royal** [comment] 2020-09-14 18:42
Custom commands are currently supported, so I don't believe that's the issue. They aren't built into the image, but eirini will set a custom command on the container, and invoke whatever you give it through `bash -c ...`

**Comment by zrob** [comment] 2020-09-14 18:54
I haven't gotten a chance to go back and test lately.  My hunch is that this is actually related to having multiple processes.  Has anybody attempted a repro?  It was very easily repro'd using the code and manifest supplied.

**Comment by matt-royal** [comment] 2020-09-14 18:56
I just attempted to reproduce this on a recent cf-for-k8s. I believe the issue is that there is no file at `/layers/paketo-buildpacks_go-mod/app-binary/bin/main`, so the web process crashes. @zrob, when you originally did this I don't believe cf-for-k8s exposed logs well, so you didn't see the `crashed` and `failing` output. Here's what I see now:

```
cf push failing-go -f /tmp/failing-manifest.yml
Pushing app failing-go to org org / space space as admin...
Applying manifest file /private/tmp/failing-manifest.yml...
Manifest applied
Packaging files to upload...
Uploading files...
 639 B / 639 B [==========================================================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Loading secret for "gcr.io" from secret "cc-kpack-registry-auth-secret-ver-1" at location "/var/build-secrets/cc-kpack-registry-auth-secret-ver-1"
   Successfully downloaded cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000/cc-packages/99/72/997243b1-1c81-4e43-b491-7177fad60615 in path "/workspace"
   paketo-buildpacks/go-dist       0.1.0
   paketo-buildpacks/go-mod-vendor 0.0.164
   paketo-buildpacks/go-build      0.0.32
   Previous image with name "gcr.io/cf-capi-arya/cf-workloads/960bd3fe-f576-4073-80ac-aeec5cb63d83" not found
   Paketo Go Distribution Buildpack 0.1.0
   Resolving Go version
   Candidate version sources (in priority order):
   <unknown> -> ""
   <unknown> -> ""

   Selected Go version (using <unknown>): 1.14.7

   Executing build process
   Installing Go 1.14.7
   Completed in 6.464s

   Paketo Go Mod Vendor Buildpack 0.0.164
   Executing build process
   Running 'go mod vendor'
   Completed in 423ms

   Paketo Go Build Buildpack 0.0.32
   Executing build process
   Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin -buildmode pie .'
   Completed in 13.785s

   Assigning launch processes
   web: /layers/paketo-buildpacks_go-build/targets/bin/golang
   Adding layer 'launcher'
   Adding layer 'paketo-buildpacks/go-build:targets'
   Adding 1/1 app layer(s)
   Adding layer 'config'
   *** Images (sha256:2b743e9d9d48f8414b0a0a6664f302ad9de88c5b8c7bc375748cf575c7e9d6b9):
   gcr.io/cf-capi-arya/cf-workloads/960bd3fe-f576-4073-80ac-aeec5cb63d83
   gcr.io/cf-capi-arya/cf-workloads/960bd3fe-f576-4073-80ac-aeec5cb63d83:b1.20200914.184615
   Adding cache layer 'paketo-buildpacks/go-dist:go'
   Warning: Failed to export cache: failed to cache layer 'paketo-buildpacks/go-mod-vendor:mod-cache' because it has no contents
   Build successful

Waiting for app failing-go to start...

name:                failing-go
requested state:     started
isolation segment:   placeholder
routes:              failing-go.apps.matt.k8s.capi.land
last uploaded:       Mon 14 Sep 11:46:15 PDT 2020
stack:
buildpacks:

type:            web
sidecars:
instances:       0/1
memory usage:    1024M
start command:   /layers/paketo-buildpacks_go-mod/app-binary/bin/main
     state     since                  cpu    memory    disk      details
#0   crashed   2020-09-14T18:47:32Z   0.0%   0 of 1G   0 of 1G

type:            worker
sidecars:
instances:       1/1
memory usage:    1024M
start command:   sleep 1000
     state     since                  cpu    memory    disk      details
#0   running   2020-09-14T18:47:31Z   0.0%   0 of 1G   0 of 1G
Start unsuccessful

TIP: use 'cf logs failing-go --recent' for more information
FAILED
```

**Comment by zrob** [comment] 2020-09-14 19:10
yeah, looks like the buildpacks have evolved since this was opened.

that file was the previous start command provided by the buildpack, it has since moved to `/layers/paketo-buildpacks_go-build/targets/bin/workspace`

my hunch is still that it was an issue of requesting multiple process and at the time the paketo go buildpack didn't include the processes cnb.  i suspect that's how'd you'd have to repro now, rip out the process cnb and push with a valid multiprocess manifest. then we might see cc fail to handle the error cleanly.

since that's all conjecture and i no longer have repro steps, i'm ok with closing the issue unless the team feels like digging deeper

**Comment by matt-royal** [comment] 2020-09-14 19:15
@zrob I'll go ahead and close this, then.

A few notes:
- As far as I can tell, there is no `/layers/` directory in the kpack-built images, so I suspect the new command would fail as well
- The failure output tells the user to run `cf logs failing-go --recent`, but this output was not useful for me. All I saw was envoy output. In order to track this down to the actual cause, I had to use kubectl or k9s to get the actual container logs. This is not ideal. `cf` doesn't currently provide a way to scope logs to a specific process, which may help here. We also may want to consider omitting the envoy output entirely. I'll follow up about this in the cf-for-k8s slack channel.

**Closed by matt-royal** 2020-09-14 19:15 UTC
Labels: in progress, k8s

**Comment by matt-royal** [comment] 2020-09-14 22:29
I'm happy to report that the latest version of cf-for-k8s has good output for this scenario:

```
$ cf push go-failing2 -f /tmp/failing-manifest.yml -p ~/workspace/cf-acceptance-tests/assets/golang/
Pushing app go-failing2 to org org / space space as admin...
Applying manifest file /private/tmp/failing-manifest.yml...
Manifest applied
Packaging files to upload...
Uploading files...
 639 B / 639 B [==========================================================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Loading secret for "gcr.io" from secret "cc-kpack-registry-auth-secret-ver-1" at location "/var/build-secrets/cc-kpack-registry-auth-secret-ver-1"
   Successfully downloaded cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000/cc-packages/3a/34/3a349a0b-c041-4c9c-8ea2-db76e2289387 in path "/workspace"
   3 of 4 buildpacks participating
   paketo-buildpacks/go-dist       0.1.0
   paketo-buildpacks/go-mod-vendor 0.0.164
   paketo-buildpacks/go-build      0.0.32
   Previous image with name "gcr.io/cf-capi-arya/cf-workloads/f37130e6-a9a8-4f09-8fb4-ee8b14324a0b" not found
   Paketo Go Distribution Buildpack 0.1.0
   Resolving Go version
   Candidate version sources (in priority order):
   <unknown> -> ""
   <unknown> -> ""

   Selected Go version (using <unknown>): 1.14.7

   Executing build process
   Installing Go 1.14.7
   Completed in 6.206s

   Paketo Go Mod Vendor Buildpack 0.0.164
   Executing build process
   Running 'go mod vendor'
   Completed in 90ms

   Paketo Go Build Buildpack 0.0.32
   Executing build process
   Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin -buildmode pie .'
   Completed in 14.36s

   Assigning launch processes
   web: /layers/paketo-buildpacks_go-build/targets/bin/golang
   Adding layer 'launcher'
   Adding layer 'paketo-buildpacks/go-build:targets'
   Adding 1/1 app layer(s)
   Adding layer 'config'
   *** Images (sha256:e74b3ff6c980d4746023a7c1443cd86d4e65611194362f329dd3704b6017c697):
   gcr.io/cf-capi-arya/cf-workloads/f37130e6-a9a8-4f09-8fb4-ee8b14324a0b
   gcr.io/cf-capi-arya/cf-workloads/f37130e6-a9a8-4f09-8fb4-ee8b14324a0b:b1.20200914.221453
   Adding cache layer 'paketo-buildpacks/go-dist:go'
   Warning: Failed to export cache: failed to cache layer 'paketo-buildpacks/go-mod-vendor:mod-cache' because it has no contents
   Build successful

Waiting for app go-failing2 to start...

name:                go-failing2
requested state:     started
isolation segment:   placeholder
routes:              go-failing2.apps.matt.k8s.capi.land
last uploaded:       Mon 14 Sep 15:14:53 PDT 2020
stack:
buildpacks:

type:            web
sidecars:
instances:       0/1
memory usage:    1024M
start command:   /layers/paketo-buildpacks_go-mod/app-binary/bin/main
     state     since                  cpu    memory    disk      details
#0   crashed   2020-09-14T22:15:50Z   0.0%   0 of 1G   0 of 1G

type:            worker
sidecars:
instances:       1/1
memory usage:    1024M
start command:   sleep 1000
     state     since                  cpu    memory    disk      details
#0   running   2020-09-14T22:15:49Z   0.0%   0 of 1G   0 of 1G
Start unsuccessful

TIP: use 'cf logs go-failing2 --recent' for more information
FAILED




$ cf logs --recent go-failing2
Retrieving logs for app go-failing2 in org org / space space as admin...

   2020-09-14T15:14:42.00-0700 [API/0] OUT Added process: "web"
   2020-09-14T15:14:42.00-0700 [API/0] OUT Created app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b
   2020-09-14T15:14:43.00-0700 [API/0] OUT Applied manifest to app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b (---
   2020-09-14T15:14:43.00-0700 [API/0] OUT applications:
   2020-09-14T15:14:43.00-0700 [API/0] OUT - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
   2020-09-14T15:14:43.00-0700 [API/0] OUT   name: go-failing2
   2020-09-14T15:14:43.00-0700 [API/0] OUT   path: "/Users/pivotal/workspace/cf-acceptance-tests/assets/golang"
   2020-09-14T15:14:43.00-0700 [API/0] OUT   processes:
   2020-09-14T15:14:43.00-0700 [API/0] OUT   - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
   2020-09-14T15:14:43.00-0700 [API/0] OUT     type: web
   2020-09-14T15:14:43.00-0700 [API/0] OUT     command: "/layers/paketo-buildpacks_go-mod/app-binary/bin/main"
   2020-09-14T15:14:43.00-0700 [API/0] OUT   - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
   2020-09-14T15:14:43.00-0700 [API/0] OUT     instances: 1
   2020-09-14T15:14:43.00-0700 [API/0] OUT     type: worker
   2020-09-14T15:14:43.00-0700 [API/0] OUT     command: sleep 1000
   2020-09-14T15:14:43.00-0700 [API/0] OUT   default-route: true
   2020-09-14T15:14:43.00-0700 [API/0] OUT   env: "[PRIVATE DATA HIDDEN]"
   2020-09-14T15:14:43.00-0700 [API/0] OUT )
   2020-09-14T15:14:46.00-0700 [API/0] OUT Scaling process: "worker"
   2020-09-14T15:14:46.00-0700 [API/0] OUT Updated app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b ({})
   2020-09-14T15:14:46.00-0700 [API/0] OUT Updated app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b ({"environment_variables"=>"[PRIVATE DATA HIDDEN]"})
   2020-09-14T15:14:53.00-0700 [API/0] OUT Creating build for app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b
   2020-09-14T15:14:53.00-0700 [API/0] OUT Creating droplet for app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b
   2020-09-14T15:15:08.16-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Loading secret for "gcr.io" from secret "cc-kpack-registry-auth-secret-ver-1" at location "/var/build-secrets/cc-kpack-registry-auth-secret-ver-1"
   2020-09-14T15:15:08.54-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Successfully downloaded cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000/cc-packages/3a/34/3a349a0b-c041-4c9c-8ea2-db76e2289387 in path "/workspace"
   2020-09-14T15:15:09.29-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT 3 of 4 buildpacks participating
   2020-09-14T15:15:09.29-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT paketo-buildpacks/go-dist       0.1.0
   2020-09-14T15:15:09.29-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT paketo-buildpacks/go-mod-vendor 0.0.164
   2020-09-14T15:15:09.29-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT paketo-buildpacks/go-build      0.0.32
   2020-09-14T15:15:10.57-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Previous image with name "gcr.io/cf-capi-arya/cf-workloads/f37130e6-a9a8-4f09-8fb4-ee8b14324a0b" not found
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Paketo Go Distribution Buildpack 0.1.0
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Resolving Go version
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Candidate version sources (in priority order):
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT <unknown> -> ""
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT <unknown> -> ""
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Selected Go version (using <unknown>): 1.14.7
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Executing build process
   2020-09-14T15:15:12.34-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Installing Go 1.14.7
   2020-09-14T15:15:18.54-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Completed in 6.206s
   2020-09-14T15:15:18.54-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT
   2020-09-14T15:15:18.55-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Paketo Go Mod Vendor Buildpack 0.0.164
   2020-09-14T15:15:18.55-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Executing build process
   2020-09-14T15:15:18.55-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Running 'go mod vendor'
   2020-09-14T15:15:18.64-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Completed in 90ms
   2020-09-14T15:15:18.64-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT
   2020-09-14T15:15:18.64-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Paketo Go Build Buildpack 0.0.32
   2020-09-14T15:15:18.65-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Executing build process
   2020-09-14T15:15:18.65-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin -buildmode pie .'
   2020-09-14T15:15:33.01-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Completed in 14.36s
   2020-09-14T15:15:33.01-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT
   2020-09-14T15:15:33.01-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Assigning launch processes
   2020-09-14T15:15:33.01-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT web: /layers/paketo-buildpacks_go-build/targets/bin/golang
   2020-09-14T15:15:35.86-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Adding layer 'launcher'
   2020-09-14T15:15:36.01-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Adding layer 'paketo-buildpacks/go-build:targets'
   2020-09-14T15:15:36.24-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Adding 1/1 app layer(s)
   2020-09-14T15:15:36.24-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Adding layer 'config'
   2020-09-14T15:15:37.61-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT *** Images (sha256:e74b3ff6c980d4746023a7c1443cd86d4e65611194362f329dd3704b6017c697):
   2020-09-14T15:15:37.61-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT gcr.io/cf-capi-arya/cf-workloads/f37130e6-a9a8-4f09-8fb4-ee8b14324a0b
   2020-09-14T15:15:37.61-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT gcr.io/cf-capi-arya/cf-workloads/f37130e6-a9a8-4f09-8fb4-ee8b14324a0b:b1.20200914.221453
   2020-09-14T15:15:40.40-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Adding cache layer 'paketo-buildpacks/go-dist:go'
   2020-09-14T15:15:41.18-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Warning: Failed to export cache: failed to cache layer 'paketo-buildpacks/go-mod-vendor:mod-cache' because it has no contents
   2020-09-14T15:15:44.73-0700 [STG/dcb7822f-1578-40df-b255-cba7fea4b415] OUT Build successful
   2020-09-14T15:15:49.00-0700 [API/0] OUT Creating revision for app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b
   2020-09-14T15:15:49.00-0700 [API/0] OUT Restarted app with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b
   2020-09-14T15:15:53.03-0700 [APP/PROC/WEB/85c9b8a5-6447-4f66-9642-aa492f7e6c5a] OUT /bin/sh: 1: /layers/paketo-buildpacks_go-mod/app-binary/bin/main: not found
   2020-09-14T15:15:53.98-0700 [APP/PROC/WEB/85c9b8a5-6447-4f66-9642-aa492f7e6c5a] OUT /bin/sh: 1: /layers/paketo-buildpacks_go-mod/app-binary/bin/main: not found
   2020-09-14T15:16:04.83-0700 [APP/PROC/WEB/85c9b8a5-6447-4f66-9642-aa492f7e6c5a] OUT /bin/sh: 1: /layers/paketo-buildpacks_go-mod/app-binary/bin/main: not found
   2020-09-14T15:16:26.75-0700 [APP/PROC/WEB/85c9b8a5-6447-4f66-9642-aa492f7e6c5a] OUT /bin/sh: 1: /layers/paketo-buildpacks_go-mod/app-binary/bin/main: not found
   2020-09-14T15:16:57.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:16:57.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>3, "crash_timestamp"=>1600121786, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
   2020-09-14T15:17:11.76-0700 [APP/PROC/WEB/85c9b8a5-6447-4f66-9642-aa492f7e6c5a] OUT /bin/sh: 1: /layers/paketo-buildpacks_go-mod/app-binary/bin/main: not found
   2020-09-14T15:17:30.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:17:30.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>4, "crash_timestamp"=>1600121831, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
   2020-09-14T15:18:10.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:18:10.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>4, "crash_timestamp"=>1600121831, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
   2020-09-14T15:18:33.74-0700 [APP/PROC/WEB/85c9b8a5-6447-4f66-9642-aa492f7e6c5a] OUT /bin/sh: 1: /layers/paketo-buildpacks_go-mod/app-binary/bin/main: not found
   2020-09-14T15:19:08.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:19:08.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>5, "crash_timestamp"=>1600121913, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
   2020-09-14T15:19:49.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:19:49.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>5, "crash_timestamp"=>1600121913, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
   2020-09-14T15:20:36.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:20:36.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>5, "crash_timestamp"=>1600121913, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
   2020-09-14T15:21:17.80-0700 [APP/PROC/WEB/85c9b8a5-6447-4f66-9642-aa492f7e6c5a] OUT /bin/sh: 1: /layers/paketo-buildpacks_go-mod/app-binary/bin/main: not found
   2020-09-14T15:21:24.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:21:24.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>6, "crash_timestamp"=>1600122077, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
   2020-09-14T15:22:15.00-0700 [API/0] OUT Process has crashed with type: "web"
   2020-09-14T15:22:15.00-0700 [API/0] OUT App instance exited with guid f37130e6-a9a8-4f09-8fb4-ee8b14324a0b payload: {"instance"=>"go-failing2-space-a387ddd220-0", "index"=>0, "cell_id"=>"", "reason"=>"CrashLoopBackOff", "exit_status"=>127, "exit_description"=>"Error", "crash_count"=>6, "crash_timestamp"=>1600122077, "version"=>"274d3d38-e3c0-47b0-b085-426d10cd61d9"}
```

**Comment by matt-royal** [comment] 2020-09-14 22:42
One more update:

I tried updating the manifest to have the `web` process use this command: `/cnb/lifecycle/launcher web`. I think this was the intention of the original manifest, and the updated path under `/layers` still didn't exist. After this change the app runs perfectly.
