### ISSUE TITLE
/v2/events API includes an unsupported query param in response URL

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/cloud_controller_ng#819] opened 2017-05-09 19:51 UTC
Hi guys,

Running CF253, we identified an issue whereby using pagination against the /v2/events URL will return a response which, in the next/prev URL fields, includes a query param that is not supported (in 253 - according to the docs it is supported in current releases, but it's worth double-checking):

Running something like: `$ cf curl /v2/events?results-per-page=100` will return:

```
{
   "total_results": 402,
   "total_pages": 5,
   "prev_url": null,
   "next_url": "/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=2&results-per-page=100",
   "resources": [```

But the `order-by=timestamp` param is not supported in cf253:

`$ cf curl '/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=2&results-per-page=100'` returns:

```{
   "description": "Cannot order by: id",
   "error_code": "CF-OrderByParameterInvalid",
   "code": 10012
}```

Omitting the `order-by=id` param gets you:

```{
   "description": "Cannot order by: timestamp",
   "error_code": "CF-OrderByParameterInvalid",
   "code": 10012
}```

So it would appear that the pagination presenter is generating incorrect URLs.

**Comment by zrob** [comment] 2017-05-09 22:17
Hey @ScarletTanager 

This is a dupe of this issue https://github.com/cloudfoundry/cloud_controller_ng/issues/803 which is resolved as of CF v257.

**Closed by zrob** 2017-05-09 22:17 UTC
Labels: unscheduled
