### ISSUE TITLE
orphaned relationship between org and user after deleting a space

### ISSUE THREAD

**Issue by nicregez** [cloudfoundry/cloud_controller_ng#530] opened 2016-02-04 14:05 UTC
Let's assume I have an org and multiple spaces associated with it.
Then, let's assume a user u1 has some role on one of the spaces, let's call it s1.
Apart from this role, the user does not have any other roles neither on the org nor on any other space.

Now, when the role was created between u1 and s1, the CC silently created an entry for that user in the org-user table, used to be able to tell the user has some role on one of the spaces of the org.

Now the issue: When the space s1 is deleted, the entry in the org-user table remains. I would expect the entry in org-user to be silently deleted by the CC as the user does not have any role on any space of that org anymore.

The name of the table I am referring to is *organizations_users*

**Comment by dieucao** [comment] 2016-02-04 18:14
@nicregez I believe it's the cli that silently adds the user to that role as a convenience.
Cloud Controller does not do that.
I would suggest filing an issue with CLI on this.

**Comment by SocalNick** [comment] 2016-06-10 21:19
Updating from https://www.pivotaltracker.com/story/show/120693181

This arises when a space is deleted. If a user is only associated with that space, i.e. is a SpaceDeveloper, the user remains attached to the Org as a User.

We would like to remove the user from the Org in this case.

Steps to reproduce:

```
cf create-org awesome-org
cf create-space awesome-space -o awesome-org
cf set-space-role cool-user awesome-org awesome-space SpaceDeveloper
cf delete-space awesome-space
```

After the above, cool-user will still be able to see awesome-org, but they have no access.

**Comment by SocalNick** [comment] 2016-06-10 21:20
@sax says:

can we do this? When cf set-space-role runs it adds the user to the organization, then to the space. Of the users who have been added to the organization, we do not know which have been added through other mechanisms.

Possibilities for the logic:
* skip users when they are also managers of the organization
* skip users who are developers of other spaces within the organization
* remove all remaining users from the organization

Even if we can determine which users are safe to delete from the org, we should not delete them in the same request where we delete the space. We should probably run a delayed job to clean out the organization users.

**Comment by SocalNick** [comment] 2016-06-10 21:22
@utako says:

In the CC validations, the user needs to be a part of the organization to be given privileges in a space.

@XenoPhex 

do you know why the CLI doesn’t remove a user from an org when a space is deleted/
it makes a call to add the user to the org when the user is given a role in a space
like space developer or whatever
because the user needs to be in the org for that to happen
but as far as clean up during a delete is concerned, is there a reason why that doesn’t happen on a space delete

**Comment by SocalNick** [comment] 2016-06-10 21:22
@XenoPhex says:

Probably because when you delete a space we don't know that we should remove that user from the org. Plus we would have to confirm they don't belong to any other spaces.

**Comment by SocalNick** [comment] 2016-06-10 21:25
@nicregez I re-opened the issue and copied in the conversation from the tracker story. Note that this opens a new issues in tracker: https://www.pivotaltracker.com/story/show/121331229

**Comment by utako** [comment] 2016-06-15 19:13
Hi @nicregez,

Just to clarify, this is desired behavior on the API side. And I'd also like to reiterate that you can open an issue with the CLI team if you'd like this behavior to be changed.

I'm going to close this issue, please feel free to reopen if you'd like to make further comments.

@utako, CF CAPI Team

**Closed by utako** 2016-06-15 19:13 UTC
Labels: unscheduled
