### ISSUE TITLE
How to update droplet's process_types values

### ISSUE THREAD

**Issue by krismarc** [cloudfoundry/cloud_controller_ng#2794] opened 2022-05-06 12:07 UTC
Dear Community,
I am playing around with droplets and seems like there's no option to append some fields without creating new empty droplet and uploading bits again. Is it expected behavior? 

I am referring to this api function:
https://v3-apidocs.cloudfoundry.org/version/3.117.0/index.html#update-a-droplet

Now, to achieve my goals I have to: 
1) download bits
2) create droplet
3) upload bits
4) set new one as a current.

## Issue

There's no option to edit droplet's process types other than creating a new droplet and then uploading bits again?

## Context

I would like to edit process types of the droplet without reuploading bits. However, available 'update' option do not accept process_types field.

## Steps to Reproduce

```
# curl "https://api.***.com/v3/droplets/59d9f68f-1ab9-4721-9d5f-f10588213151"   -X PATCH   -H "Authorization: $(cf oauth-token)"   -H "Content-Type: application/json"   -d @droplet
{
  "errors": [
    {
      "detail": "Unknown field(s): 'relationships', 'process_types'",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

```
# cat droplet | jq -r .
{
  "relationships": {
    "app": {
      "data": {
        "guid": "f44d8ba6-c8ec-4811-9b9b-d1ff7d875d63"
      }
    }
  },
  "process_types": {
    "web": ".liberty/create_vars.rb wlp/usr/servers/defaultServer/runtime-vars.xml && .liberty/calculate_memory.rb && WLP_SKIP_MAXPERMSIZE=true JAVA_HOME=\"$PWD/.java\" WLP_USER_DIR=\"$PWD/wlp/usr\" exec .liberty/bin/server run defaultServer"
  }
}
```

## Expected result

By doing an update, I'd like to append current process_types keys values.

## Current result

"errors": [
    {
      "detail": "Unknown field(s): 'relationships', 'process_types'",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }

Best regards,
K.M.

**Comment by Gerg** [comment] 2022-05-09 17:39
Droplets are (mostly) immutable resources, so you cannot modify any of the properties that affect how they operate. Otherwise, you might end up in a situation where running the same droplet (a.k.a. restarting the app) would result in different running apps.

You can affect what process types are generated for an application using [an application manifest or Procfile](https://docs.cloudfoundry.org/devguide/multiple-processes.html#push-with-multiple-processes).

Closing since this is intended behavior. Feel free to open a [Discussion topic](https://github.com/cloudfoundry/cloud_controller_ng/discussions) if you would like to discuss further.

**Closed by Gerg** 2022-05-09 17:39 UTC
Labels: unscheduled
