### ISSUE TITLE
Cannot create or list tasks for my app

### ISSUE THREAD

**Issue by thausler786** [cloudfoundry/cloud_controller_ng#833] opened 2017-06-16 18:29 UTC
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Creating and indexing tasks fails due to permissioning errors.  When I try to create or list tasks for my app, I get failures that are unexpected.  CF_TRACE shows that this is because I get a 404 when trying to access the `v3/app/:guid/tasks` endpoint for POST and GET

This does not occur when I am an admin.

## Context

I have all of the roles in my space and in my org:

```
 cf space-users failedtaskorg development
Getting users in org failedtaskorg / space development as thausler+icanceltasks@pivotal.io

SPACE MANAGER
  redacted@pivotal.io

SPACE DEVELOPER
  redacted@pivotal.io

SPACE AUDITOR
  redacted@pivotal.io

cf org-users failedtaskorg
Getting users in org failedtaskorg as thausler+icanceltasks@pivotal.io...

ORG MANAGER
  redacted@pivotal.io

BILLING MANAGER
  redacted@pivotal.io

ORG AUDITOR
  redacted@pivotal.io
```

Furthermore, I can see the app that I am creating my task off of:

```
cf app aora
Showing health and status for app aora in org failedtaskorg / space development as redacted@pivotal.io...
OK

requested state: stopped
instances: 0/1
usage: 256M x 1 instances
urls: aora.a1-app.cf-app.com
last uploaded: Tue Jun 13 20:43:53 UTC 2017
stack: cflinuxfs2
buildpack: ruby 1.6.40

There are no running instances of this app.
```

## Steps to Reproduce

1. Create a space in an org and give yourself all roles
1. Create an app
1. Try to run a task off of that app: `cf run-task aora 'echo foo'`
1. Try to list tasks off of the app: `cf tasks aora`

## Expected result

I expect my task to be created and my tasks to be listed.

## Current result

```
Creating task for app aora in org failedtaskorg / space development as redacted@pivotal.io...
App not found
FAILED
```
```
Getting tasks for app aora in org failedtaskorg / space development as thausler+icanceltasks@pivotal.io...
App not found
FAILED
```
## Possible Fix

Use v2 access classes for app to permission the v3 task resource. What could go wrong.

**Comment by zrob** [comment] 2017-06-22 19:13
@thausler786 i'm not able to reproduce this when logging in as a SpaceDeveloper

**Comment by aashah** [comment] 2017-06-22 21:15
@thausler786 I was also not able to reproduce. I tried giving the user "all the roles" like mentioned, but it did not prevent me from running/listing tasks.

I did something like (omitting output for everything but the last two commands):

```
$ cf create-org test
$ cf create-space -o test test
$ cf target -o test -o test
$ cf create-user testuser password
$ cf set-org-role testuser test OrgManager
$ cf set-org-role testuser test BillingManager
$ cf set-org-role testuser test OrgAuditor
$ cf set-space-role testuser test test SpaceManager
$ cf set-space-role testuser test test SpaceDeveloper
$ cf set-space-role testuser test test SpaceAuditor
$ cf auth testuser password
$ cf target -o test -s test
$ cf push app
$ cf run-task app 'echo foo'
Creating task for app app in org test / space test as testuser...
OK

Task has been submitted successfully for execution.
task name:   8cc90264
task id:     1
$ cf tasks app
Getting tasks for app app in org test / space test as testuser...
OK

id   name       state       start time                      command
1    8cc90264   SUCCEEDED   Thu, 22 Jun 2017 21:12:49 UTC   echo foo
```

**Comment by mikexuu** [comment] 2017-07-06 17:35
Hello @thausler786 !

We're closing this issue for now since it has been difficult to reproduce. Please feel free to re-open this issue if you see the problem again.

Thanks,
@anniesing & @mikexuu

**Closed by mikexuu** 2017-07-06 17:35 UTC
Labels: unscheduled
