### ISSUE TITLE
"result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng." when updating api_z1 instance during deployment

### ISSUE THREAD

**Issue by jeffrey-hui** [cloudfoundry/cloud_controller_ng#1170] opened 2018-06-27 14:30 UTC
## Issue

Hello,
I am trying to deploy an instance of CF on vSphere with the Bosh Director using cf-release. 
I get the error of a post script failing for cloud_controller_ng when updating the instance of api_z1 during deployment. 

````
Task 13693

Task 13693 | 21:52:51 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
Task 13693 | 21:52:52 | Preparing deployment: Preparing deployment (00:00:01)
Task 13693 | 21:52:55 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 13693 | 21:52:56 | Updating instance consul_z1: consul_z1/57728e13-93a2-469e-8b17-f0ca19363085 (0) (canary) (00:00:59)
Task 13693 | 21:53:55 | Updating instance nats_z1: nats_z1/1eb4af0d-8448-4967-b79a-9e8c05a8df90 (0) (canary) (00:00:54)
Task 13693 | 21:54:49 | Updating instance etcd_z1: etcd_z1/fbf797f5-54a3-48cf-891c-373cb2a1cc63 (0) (canary) (00:01:03)
Task 13693 | 21:55:52 | Updating instance blobstore_z1: blobstore_z1/39905bd7-fc9d-4d68-a4d6-ec04cf61a373 (0) (canary) (00:01:05)
Task 13693 | 21:56:57 | Updating instance postgres_z1: postgres_z1/feca6f72-0b88-4306-90f9-9322e975c61e (0) (canary) (00:01:01)
Task 13693 | 21:57:58 | Updating instance uaa_z1: uaa_z1/3e1c08a3-1457-4b7f-9527-b99e0b4a84d5 (0) (canary) (00:01:22)
Task 13693 | 21:59:20 | Updating instance api_z1: api_z1/840806db-e476-49b1-bbe9-8a654090e52b (0) (canary)api_z1/840806db-e476-49b1-bbe9-8a654090e52b                             failing -
 (00:01:17)
                     L Error: Action Failed get_task: Task 36540cda-e20e-4690-6ae0-e6eb51456e41 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.
Task 13693 | 22:00:37 | Error: Action Failed get_task: Task 36540cda-e20e-4690-6ae0-e6eb51456e41 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.

Task 13693 Started  Tue Jun 26 21:52:51 UTC 2018
Task 13693 Finished Tue Jun 26 22:00:37 UTC 2018
Task 13693 Duration 00:07:46
Task 13693 error

Updating deployment:
  Expected task '13693' to succeed but state is 'error'

Exit code 1
````

After going through the logs, I found that api_z1 fails when trying to connect to the blobstore, receiving a “403 forbidden” message. The logs don’t explicitly indicate a URL at which it fails to connect into but the blobstore IP (.81) is pingable and reachable from the troubled instance. 

This is the last update before the timeout inside **controller_ng.log**

```
{
  "timestamp": 1530044677.6274924,
  "message": "Buildpack staticfile_buildpack failed to install or update. Error: #<CloudController::Blobstore::BlobstoreError: Could not create object, 403/<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n>",
  "log_level": "error",
  "source": "cc.background",
  "data": {},
  "thread_id": 47288642072400,
  "fiber_id": 47288682226500,
  "process_id": 24603,
  "file": "/var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb",
  "lineno": 38,
  "method": "rescue in perform"
}
```
and the **post-start.stderr.log** also contains a similar 403 error when accessing the blobstore and static-buildpack also fails to install. 

```
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ CC_JOB_DIR=/var/vcap/jobs/cloud_controller_ng
+ CONFIG_DIR=/var/vcap/jobs/cloud_controller_ng/config
+ CC_PACKAGE_DIR=/var/vcap/packages/cloud_controller_ng
+ export CLOUD_CONTROLLER_NG_CONFIG=/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml
+ CLOUD_CONTROLLER_NG_CONFIG=/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml
+ export BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
+ BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
+ source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh
++ export PATH=/var/vcap/packages/ruby-2.4/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/var/vcap/packages/ruby-2.4/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ source /var/vcap/packages/capi_utils/syslog_utils.sh
++ basename /var/vcap/jobs/cloud_controller_ng/bin/post-start
+ tee_output_to_sys_log cloud_controller_ng.post-start
+ declare log_name=cloud_controller_ng.post-start
+ exec
+ exec
++ prepend_datetime
++ awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }'
++ prepend_datetime
++ awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }'
++ tee -a /dev/fd/63
++ tee -a /dev/fd/63
+++ logger -p user.error -t vcap.cloud_controller_ng.post-start.stderr
+++ logger -p user.info -t vcap.cloud_controller_ng.post-start.stdout
[2018-06-26 20:12:33+0000] + main
[2018-06-26 20:12:33+0000] + install_buildpacks
[2018-06-26 20:12:33+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2018-06-26 20:12:33+0000] + chpst -u vcap:vcap bundle exec rake buildpacks:install
[2018-06-26 20:12:37+0000] rake aborted!
[2018-06-26 20:12:37+0000] CloudController::Blobstore::BlobstoreError: Could not create object, 403/<html>
[2018-06-26 20:12:37+0000] <head><title>403 Forbidden</title></head>
[2018-06-26 20:12:37+0000] <body bgcolor="white">
[2018-06-26 20:12:37+0000] <center><h1>403 Forbidden</h1></center>
[2018-06-26 20:12:37+0000] <hr><center>nginx</center>
[2018-06-26 20:12:37+0000] </body>
[2018-06-26 20:12:37+0000] </html>
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/webdav/dav_client.rb:101:in `block in cp_to_blobstore'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/webdav/dav_client.rb:94:in `open'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/webdav/dav_client.rb:94:in `cp_to_blobstore'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:48:in `block in cp_to_blobstore'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:139:in `with_retries'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:42:in `cp_to_blobstore'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:22:in `upload_buildpack'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb:27:in `perform'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:59:in `run_canary'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:42:in `install'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/tasks/buildpacks.rake:6:in `block (3 levels) in <top (required)>'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:15:in `setup_environment'
[2018-06-26 20:12:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/tasks/buildpacks.rake:5:in `block (2 levels) in <top (required)>'
[2018-06-26 20:12:37+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
[2018-06-26 20:12:37+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `load'
[2018-06-26 20:12:37+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `<main>'
[2018-06-26 20:12:37+0000] Tasks: TOP => buildpacks:install
[2018-06-26 20:12:37+0000] (See full trace by running task with --trace)
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ CC_JOB_DIR=/var/vcap/jobs/cloud_controller_ng
+ CONFIG_DIR=/var/vcap/jobs/cloud_controller_ng/config
+ CC_PACKAGE_DIR=/var/vcap/packages/cloud_controller_ng
+ export CLOUD_CONTROLLER_NG_CONFIG=/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml
+ CLOUD_CONTROLLER_NG_CONFIG=/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml
+ export BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
+ BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
+ source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh
++ export PATH=/var/vcap/packages/ruby-2.4/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/var/vcap/packages/ruby-2.4/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ source /var/vcap/packages/capi_utils/syslog_utils.sh
++ basename /var/vcap/jobs/cloud_controller_ng/bin/post-start
+ tee_output_to_sys_log cloud_controller_ng.post-start
+ declare log_name=cloud_controller_ng.post-start
+ exec
+ exec
++ prepend_datetime
++ awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }'
++ tee -a /dev/fd/63
++ prepend_datetime
++ awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }'
++ tee -a /dev/fd/63
+++ logger -p user.error -t vcap.cloud_controller_ng.post-start.stderr
+++ logger -p user.info -t vcap.cloud_controller_ng.post-start.stdout
[2018-06-26 20:24:34+0000] + main
[2018-06-26 20:24:34+0000] + install_buildpacks
[2018-06-26 20:24:34+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2018-06-26 20:24:34+0000] + chpst -u vcap:vcap bundle exec rake buildpacks:install
[2018-06-26 20:24:37+0000] rake aborted!
[2018-06-26 20:24:37+0000] CloudController::Blobstore::BlobstoreError: Could not create object, 403/<html>
[2018-06-26 20:24:37+0000] <head><title>403 Forbidden</title></head>
[2018-06-26 20:24:37+0000] <body bgcolor="white">
[2018-06-26 20:24:37+0000] <center><h1>403 Forbidden</h1></center>
[2018-06-26 20:24:37+0000] <hr><center>nginx</center>
[2018-06-26 20:24:37+0000] </body>
[2018-06-26 20:24:37+0000] </html>
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/webdav/dav_client.rb:101:in `block in cp_to_blobstore'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/webdav/dav_client.rb:94:in `open'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/webdav/dav_client.rb:94:in `cp_to_blobstore'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:48:in `block in cp_to_blobstore'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:139:in `with_retries'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:42:in `cp_to_blobstore'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:22:in `upload_buildpack'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb:27:in `perform'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:59:in `run_canary'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:42:in `install'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/tasks/buildpacks.rake:6:in `block (3 levels) in <top (required)>'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:15:in `setup_environment'
[2018-06-26 20:24:37+0000] /var/vcap/data/packages/cloud_controller_ng/7200755149d438b80d0fd1205f7ed9a9d52c6a03/cloud_controller_ng/lib/tasks/buildpacks.rake:5:in `block (2 levels) in <top (required)>'
[2018-06-26 20:24:37+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
[2018-06-26 20:24:37+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `load'
[2018-06-26 20:24:37+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `<main>'
[2018-06-26 20:24:37+0000] Tasks: TOP => buildpacks:install
[2018-06-26 20:24:37+0000] (See full trace by running task with --trace)
```
I'm not sure how to go about fixing this error, has anyone ever come across an error during deployment like this? Any help would be appreciated.

**Comment by zrob** [comment] 2018-06-29 16:53
Hey @jeffrey-hui 

It seems clear that there is a misconfiguration that is preventing CC from accessing the blobstore.  You can review these docs for blobstore configuration information: https://docs.cloudfoundry.org/deploying/common/cc-blobstore-config.html

Since this isn't a bug with CC I'm closing the issue.  For additional help you can reach out to the [capi slack channel](https://cloudfoundry.slack.com/messages/C07C04W4Q)

**Closed by zrob** 2018-06-29 16:53 UTC
Labels: unscheduled

**Comment by tcdowney** [comment] 2018-07-06 16:48
Investigated this a bit more with @jeffrey-hui,  the issue was caused by the `cloud_controller_ng` job attempting to access the WebDav blobstore on an IP outside of the default ranges it allows:

https://github.com/cloudfoundry/capi-release/blob/c778736087a50d59d02f15c282afb5fbfb490ab1/jobs/blobstore/spec#L36-L44

We confirmed this by running `dig blobstore.service.cf.internal` from the `api` instance and saw that the IP address that it resolved to was outside of this range (but was still an expected IP address for the given network). After configuring `blobstore.internal_access_rules` with that network the deployment succeeded.
