### ISSUE TITLE
invalid user guid accepted by PUT /v2/organizations/:guid/billing_managers/:guid API

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cloud_controller_ng#918] opened 2017-09-27 23:15 UTC
## Issue

API response inconsistency, when using an invalid user guid:

```
d:\projects>cf curl /v2/spaces/3261e2ae-ed69-4eb7-a55d-835c36fd0610/developers/1234 -X PUT
{
   "description": "1234",
   "error_code": "CF-InvalidRelation",
   "code": 1002
}
d:\projects>cf curl /v2/organizations/c87b1efc-0578-4267-b64a-ae08333e3ba3/billing_managers/1234 -X PUT -v

REQUEST: [2017-09-28T01:43:45+09:00]
PUT /v2/organizations/c87b1efc-0578-4267-b64a-ae08333e3ba3/billing_managers/1234 HTTP/1.1
...

RESPONSE: [2017-09-28T01:43:45+09:00]
HTTP/1.1 201 Created
```

Shouldn't the latter call fail like the first one did?

## Expected result

Both APIs to return with a similar error.

**Comment by Gerg** [comment] 2017-10-16 22:12
Thanks for submitting this issue @dkoper. We will investigate an get back to you with more information.

Thanks,
Greg

**Comment by tcdowney** [comment] 2017-10-25 19:00
@dkoper we are able to reproduce your issue on the latest CAPI release. We'll look into why this isn't erroring as expected.

**Comment by tcdowney** [comment] 2017-10-25 21:28
@dkoper 

@ljfranklin and I did a bit of investigation and neither the org nor the space endpoints actually do any validation around the user guid belonging to a valid UAA user.

The `CF-InvalidRelation` error you're seeing after doing `cf curl /v2/spaces/3261e2ae-ed69-4eb7-a55d-835c36fd0610/developers/1234` is due to the fact that user `1234` is not a user within the org and has nothing to do with the fact that it isn't a valid UAA user.

If you were to make a call like `cf curl -v /v2/organizations/c87b1efc-0578-4267-b64a-ae08333e3ba3/users/1234 -X PUT` first, the call to the spaces endpoint would have succeeded.

I think the real problem here is that the error itself isn't very understandable.

@zrob I think we could actually update the error messages pretty easily here:
https://github.com/cloudfoundry/cloud_controller_ng/blob/723c2585a73fd34c496f288eb7328f85e80c2756/app/models/runtime/space.rb#L184-L194

Right now it's just passing the `user.guid` into the error and using that as the message. We could pass it something.. better. 🍾

**Comment by selzoc** [comment] 2019-07-10 18:56
Closing as we're not really doing `v2` work anymore

**Closed by selzoc** 2019-07-10 18:56 UTC
Labels: PM Review, bug, unscheduled
