### ISSUE TITLE
Unable to delete apps on K8s.

### ISSUE THREAD

**Issue by weymanf** [cloudfoundry/cloud_controller_ng#1865] opened 2020-09-24 18:50 UTC
## Issue

I am unable to delete apps on CF deployed by TAS4K8s.

## Context

My pipeline runs a task to cleanup and deploy test apps. They are failing on deleting a space because apps are unable to be deleted. We are getting an unknown error when trying to delete a space: 
```
cf delete-space amjs-test-space
Really delete the space amjs-test-space? [yN]: y
Deleting space amjs-test-space in org amjs-test-org as admin...
Job (b17165d3-400a-42d4-9aa6-d39eb57c70e1) failed: An unknown error occurred.
FAILED
```

We get a 500 when trying to delete an app:

```
cf delete amjs-test-app

Really delete the app amjs-test-app?> y
Deleting app amjs-test-app in org amjs-test-org / space amjs-test-space as admin...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

This is the cf-for-k8s version is running. I don't know the corresponding ccng version

```
  - git:
      commitTitle: Autobump stack images
      sha: 221ac187883e3ffd4e456705fbbe738f577b2338
    path: github.com/cloudfoundry/cf-for-k8s
```

Here is the slack conversation that might contain more info: https://cloudfoundry.slack.com/archives/CCRLX88DD/p1600902653002500

## Steps to Reproduce

1. Deploy Cloudfoundry using https://github.com/pivotal/tanzu-application-service at 221ac187883e3ffd4e456705fbbe738f577b2338 or deploy cf-for-k8s version above
1. Try to delete an app.

## Expected result

The app should be deleted.

## Current result

The app fails to delete.

Here are some cc logs.
```
{"timestamp":"2020-09-23T23:20:20.880750755Z","message":"Deleting app: 626b1f32-4838-45c2-adf2-8fa216839b4d","log_level":"info","source":"cc.action.app_delete","data":{"request_guid":"9c0a61b2-4c42-4cdf-92b2-1f5867110942::68e548bf-ea19-40a4-bbb8-0c844a1d1119"},"thread_id":47042830870000,"fiber_id":4704289151
9340,"process_id":1,"file":"/cloud_controller_ng/app/actions/app_delete.rb","lineno":37,"method":"block in delete"}                                                                                                                                                                                                  
{"timestamp":"2020-09-23T23:20:20.934266448Z","message":"Failed to resolve update conflicts after 3 retries: ","log_level":"error","source":"kubernetes.update_reapply","data":{"request_guid":"9c0a61b2-4c42-4cdf-92b2-1f5867110942::68e548bf-ea19-40a4-bbb8-0c844a1d1119"},"thread_id":47042830870000,"fiber_id":47
042891519340,"process_id":1,"file":"/cloud_controller_ng/lib/kubernetes/update_reapply_client.rb","lineno":43,"method":"block in retry_on_conflict"}                                                                                                                                                                 
{"timestamp":"2020-09-23T23:20:20.961807419Z","message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"undefined method `spec' for nil:NilClass\", \"error_code\"=>\"CF-spec\", \"backtrace\"=>[\
"/cloud_controller_ng/lib/kubernetes/route_resource_manager.rb:51:in `block in update_destinations'\", \"/cloud_controller_ng/lib/kubernetes/update_reapply_client.rb:18:in `block in apply_route_update'\", \"/cloud_controller_ng/lib/kubernetes/update_reapply_client.rb:44:in `block in retry_on_conflict'\", \"/
usr/local/lib/ruby/gems/2.5.0/gems/retryable-3.0.5/lib/retryable.rb:72:in `retryable'\", \"/cloud_controller_ng/lib/kubernetes/update_reapply_client.rb:42:in `retry_on_conflict'\", \"/cloud_controller_ng/lib/kubernetes/update_reapply_client.rb:17:in `apply_route_update'\", \"/cloud_controller_ng/lib/kubernetes/route_resource_manager.rb:50:in `update_destinations'\", \"/cloud_controller_ng/app/actions/route_mapping_delete.rb:34:in `block (2 levels) in delete'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.35.0/lib/sequel/database/transactions.rb:229:in `block in transaction'\"
```

## Possible Fix

Tim Downey had some theories:  "The code is trying to update destinations on a route in k8s... but there might be a race condition there if the route itself is also being deleted (perhaps by a different async job?)"

**Comment by reid47** [comment] 2020-09-29 18:02
As a workaround, we were able to delete the route for the app first (using `cf delete-route`), and then successfully delete the app with `cf delete`. Two apps in our test space had to be deleted in this way.

We'll let you know if we get into this state again.

We wanted to call out that we're now using an external DB (Postgres) for our deployment given the upstream changes in TAS4K8s. We have a separate investigation to see if we're not deleting things out of the database properly; not sure if that would have any impact on this issue.

**Comment by matt-royal** [comment] 2020-10-20 00:06
@reid47 @weymanf GKE is having some problems ATM that are preventing me from reproducing this. For when that's over, is there anything special about the app that's giving you this problem? We're not seeing our pipeline fail on deleting apps, so I suspect there's something unusual going on here.

**Comment by reid47** [comment] 2020-10-20 00:09
cc @belinda-liu to keep me honest here, but I think we resolved this by making sure our database was torn down and recreated each time we re-deployed cf-for-k8s. Since our Postgres DB was created separately, it wouldn't be deleted with our `kapp delete`. Then it would be re-used when the env deployed again. I think this led to some weird state preserved between deployments. Not sure it's reproducible generally.

**Comment by matt-royal** [comment] 2020-10-20 00:11
@reid47 If that's the case, then I'd suggest closing this issue. We don't support reusing an old DB on a new cf-for-k8s cluster, so unusual behavior would be expected.

**Comment by reid47** [comment] 2020-10-20 00:12
Yeah, that makes sense. I'll confirm with Belinda tomorrow, but then we'll close it if what I said is true.

**Comment by reid47** [comment] 2020-10-20 17:07
Closing this issue. Thanks!

As a final note, we wanted to point out that it's kind of a weird & confusing error (a 500, then `undefined method 'spec' for nil:NilClass` in the logs) that didn't really point us to anything about our external DB. That was a lucky hunch. Not sure anyone else will end up in the spot we were in, but just recording this for posterity.

**Closed by reid47** 2020-10-20 17:07 UTC
Labels: k8s, unscheduled
