### ISSUE TITLE
Apps cannot unmap routes when their buildpack no longer exists

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cloud_controller_ng#1066] opened 2018-01-22 23:03 UTC
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

If an app was deployed with a buildpack that has since been deleted, unmapping its routes fails, preventing blue-green deployments.

## Context

`cf unmap-route` fails to unmap routes from apps whose buildpack has been removed

## Steps to Reproduce

1. push an app via buildpack-x
2. delete buildpack-x
3 cf unmap-route the app's route

## Expected result

The route should unmap.

## Current result

The unmapping fails:
```
$ cf unmap-route my-app -n my-app example.com
Removing route my-app.example.com from app my-app in org my-app / space dev as gfranks...
FAILED
Server error, status code: 400, error code: 100001, message: The app is invalid: buildpack nodejs_buildpack_v1_5_17 is not valid public url or a known buildpack name
```

## Possible Fix

Potentially an issue with model validations in the ORM due to foreign key constraints on buildpacks for an app?

**Comment by ericpromislow** [comment] 2018-02-27 23:53
Hi @geofffranks 

Thanks for submitting this report. Unfortunately, I couldn't reproduce it, going by the following script: ```
$ git clone https://github.com/cloudfoundry-community/cppcms-buildpack.git

$ cd cppcms-buildpack
$ zip -r ../cppcms.zip *

$ cd ..
$ cf create-buildpack cppcms_buildpack $PWD/cppcms.zip  9 --enable

$ cd cppcms-buildpack/test/fixtures/helloworld

$ cf push hwcpp01 -b cppcms_buildpack

# Make sure it works
$ curl hwcpp01.quasar-pirate.capi.land
<html>
<body>
  <h1>Hello World</h1>
</body>
</html>

$ cf delete-buildpack -f cppcms_buildpack

$ cf unmap-route hwcpp01 quasar-pirate.capi.land -n hwcpp01
Removing route hwcpp01.quasar-pirate.capi.land from app hwcpp01 in org org / space space as admin...
OK

$ cf a
Getting apps in org org / space space as admin...
OK

name       requested state   instances   memory   disk   urls
hwcpp01    started           1/1         256M     1G     hwcpp01.quasar-pirate.capi.land

$ f unmap-route hwcpp01 quasar-pirate.capi.land -n hwcpp01
Removing route hwcpp01.quasar-pirate.capi.land from app hwcpp01 in org org / space space as admin...
OK

$ cf a
Getting apps in org org / space space as admin...
OK

name       requested state   instances   memory   disk   urls
hwcpp01    started           1/1         256M     1G     <NO ROUTE>
```

If you run `cf curl /v2/info`, what does the `api_version` field report?  I looked at the current state of the database, and I don't see a dependency like the one you described among apps, routes, and buildpacks.

Thanks,
Eric Promislow, CAPI Community Team

**Comment by geofffranks** [comment] 2018-03-05 15:07
We have a few different environments, one at 2.82, one at 2.85, and one at 2.94. I believe we encountered this in the env running 2.85.

**Comment by lisamcho** [comment] 2018-03-06 21:50
Looks like this isn't an issue with the current release. We typically don't support older releases. Can you please close the issue? @geofffranks

**Comment by geofffranks** [comment] 2018-03-06 22:51
Thanks for taking a look!

**Closed** 2018-03-06 22:51 UTC
Labels: unscheduled
