### ISSUE TITLE
/v2/organizations/GUID/summary returns no spaces when queried with cloud_controller.admin_read_only scope

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry/cloud_controller_ng#756] opened 2017-01-03 21:16 UTC
## Issue

When querying /v2/organizations/GUID/summary using cloud_controller.admin_read_only scope I get an empty list of spaces. The same endpoint, for the same GUID, returns all the existing spaces if I switch to a user with cloud_controller.admin scope.

## Steps to Reproduce

1. Create a user with cloud_controller.admin_read_only scope
3. cf login as that user
2. cf curl /v2/organizations/GUID/summary

## Expected result

The response should include all the existing spaces in the org

## Current result

The list of spaces is empty. Here's an example from my environment:
{
  "guid": "b7d24aa9-3c62-46ae-a798-dca41e61fe11",
  "name": "system",
  "status": "active",
  "spaces": []
}

There are actually 4 spaces in that org.

Thanks,

**Comment by michaelxupiv** [comment] 2017-01-13 19:04
Hey @mkuratczyk,

Thanks for submitting this issue. I have pushed a [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/6a383ba5a527a90aebd1bd22815a9a098fe40176) to fix this. The intended behavior should be available in the next capi-release. Closing this issue for now, feel free to reopen if you feel like I haven't addressed your issue.

Thanks,
CAPI Community - @michaelxupiv

**Closed by michaelxupiv** 2017-01-13 19:04 UTC
Labels: in progress
