### ISSUE TITLE
repushing an existing process fails to trigger diego synchronously

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#1271] opened 2018-12-08 01:45 UTC
Run https://github.com/cloudfoundry/capi-bara-tests/blob/0bfba64df3f77a38af1821dc600c5ac71c0c24e4/rolling_deployments/mixed_deployment.go#L20 on a bosh-lite, with or without deployments, with `cc.diego_sync.frequency_in_seconds` set to something good and healthy like 600 seconds.

Watch the test fail

**Comment by charleshansen** [comment] 2018-12-10 18:39
For reference, I believe this is a dupe of a bug already prioritized in tracker https://www.pivotaltracker.com/story/show/162465589

**Comment by zrob** [comment] 2018-12-20 23:11
@ericpromislow was this resolved in the linked story?

**Comment by ericpromislow** [comment] 2018-12-21 21:51
This still fails. If I write a slightly different test that calls for turning the clock off, instead of using the large frequency-delay, the test passes.

**Comment by cwlbraa** [comment] 2020-01-23 00:46
closing as fixed! https://www.pivotaltracker.com/story/show/162465589/comments/197875554

**Closed by cwlbraa** 2020-01-23 00:46 UTC
Labels: unscheduled
